version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: nodeland-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HarestuaArendalStavanger@1
      MYSQL_DATABASE: nodeland
      MYSQL_USER: nodeland
      MYSQL_PASSWORD: HarestuaArendalStavanger@1
    volumes:
      - db-data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pHarestuaArendalStavanger@1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodeland-backend
    command: npm run dev                # nodemon watches and reloads your server
    working_dir: /app
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app                   # mount your server source
      - /app/node_modules               # keep dependencies in container
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:18-alpine               # use Node for Vite dev server
    container_name: nodeland-frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./client:/app                   # mount your client source
      - /app/node_modules               # keep deps in container
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"       # ensure file‐watching works in Docker
    depends_on:
      - backend

volumes:
  db-data:
