# docker-compose.dev.yml
services:
  db:
    image: mysql:8.0
    container_name: nodeland-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HarestuaArendalStavanger@1
      MYSQL_DATABASE: nodeland
      MYSQL_USER: nodeland
      MYSQL_PASSWORD: HarestuaArendalStavanger@1
    volumes:
      - db-data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    # <— changed host port to 3307 to avoid conflict with local MySQL
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pHarestuaArendalStavanger@1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodeland-backend
    command: npm run dev
    working_dir: /app
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nodeland-frontend
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:80"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  db-data:
