export function parseRaw(raw) {
  const parts = raw.trim().split(/\s+/);
  return {
    ts:                          Date.now(),
    station_id:                  parseFloat(parts[0]),
    average_windspeed:           parseFloat(parts[1]),
    current_windspeed:           parseFloat(parts[2]),
    wind_dir:                    parseFloat(parts[3]),
    out_temp:                    parseFloat(parts[4]),
    out_hum:                     parseFloat(parts[5]),
    barometer:                   parseFloat(parts[6]),
    day_rain:                    parseFloat(parts[7]),
    month_rain:                  parseFloat(parts[8]),
    year_rain:                   parseFloat(parts[9]),
    rain_rate_mm_min:            parseFloat(parts[10]),
    rain_rate_max_mm_min:        parseFloat(parts[11]),
    in_temp:                     parseFloat(parts[12]),
    in_hum:                      parseFloat(parts[13]),
    soil_temp:                   parseFloat(parts[14]),
    forecast_icon_code:          parseInt(parts[15], 10),
    wmr968_extra_temp:           parseFloat(parts[16]),
    wmr968_extra_hum:            parseFloat(parts[17]),
    wmr968_extra_sensor:         parseInt(parts[18], 10),
    yesterday_rain:              parseFloat(parts[19]),
    extra_temp_sensor_1:         parseFloat(parts[20]),
    extra_temp_sensor_2:         parseFloat(parts[21]),
    extra_temp_sensor_3:         parseFloat(parts[22]),
    extra_temp_sensor_4:         parseFloat(parts[23]),
    extra_temp_sensor_5:         parseFloat(parts[24]),
    extra_temp_sensor_6:         parseFloat(parts[25]),
    extra_hum_sensor_1:          parseFloat(parts[26]),
    extra_hum_sensor_2:          parseFloat(parts[27]),
    extra_hum_sensor_3:          parseFloat(parts[28]),
    measurement_hour:            parseInt(parts[29], 10),
    measurement_minute:          parseInt(parts[30], 10),
    measurement_second:          parseInt(parts[31], 10),
    location_label:              parts[32],
    lightning_count_since_noon:  parseInt(parts[33], 10),
    solar_percent_of_max:        parseInt(parts[34], 10),
    measurement_day:             parseInt(parts[35], 10),
    measurement_month:           parseInt(parts[36], 10),
    wmr968_batt1:                parseFloat(parts[37]),
    wmr968_batt2:                parseFloat(parts[38]),
    wmr968_batt3:                parseFloat(parts[39]),
    wmr968_batt4:                parseFloat(parts[40]),
    wmr968_batt5:                parseFloat(parts[41]),
    wmr968_batt6:                parseFloat(parts[42]),
    wmr968_batt7:                parseFloat(parts[43]),
    wind_chill:                  parseFloat(parts[44]),
    humidex:                     parseFloat(parts[45]),
    max_temp_today:              parseFloat(parts[46]),
    min_temp_today:              parseFloat(parts[47]),
    current_condition_icon:      parseInt(parts[48], 10),
    sky_condition_text:          parts[49],
    baro_trend_last_hour:        parseFloat(parts[50]),
    windspeed_hour_01:           parseFloat(parts[51]),
    windspeed_hour_02:           parseFloat(parts[52]),
    windspeed_hour_03:           parseFloat(parts[53]),
    windspeed_hour_04:           parseFloat(parts[54]),
    windspeed_hour_05:           parseFloat(parts[55]),
    windspeed_hour_06:           parseFloat(parts[56]),
    windspeed_hour_07:           parseFloat(parts[57]),
    windspeed_hour_08:           parseFloat(parts[58]),
    windspeed_hour_09:           parseFloat(parts[59]),
    windspeed_hour_10:           parseFloat(parts[60]),
    windspeed_hour_11:           parseFloat(parts[61]),
    windspeed_hour_12:           parseFloat(parts[62]),
    windspeed_hour_13:           parseFloat(parts[63]),
    windspeed_hour_14:           parseFloat(parts[64]),
    windspeed_hour_15:           parseFloat(parts[65]),
    windspeed_hour_16:           parseFloat(parts[66]),
    windspeed_hour_17:           parseFloat(parts[67]),
    windspeed_hour_18:           parseFloat(parts[68]),
    windspeed_hour_19:           parseFloat(parts[69]),
    windspeed_hour_20:           parseFloat(parts[70]),
    max_wind_gust:               parseFloat(parts[71]),
    dew_point:                   parseFloat(parts[72]),
    cloud_height:                parseFloat(parts[73]),
    current_date:                parts[74],
    max_humidex:                 parseFloat(parts[75]),
    min_humidex:                 parseFloat(parts[76]),
    max_windchill:               parseFloat(parts[77]),
    min_windchill:               parseFloat(parts[78]),
    uv_index:                    parseFloat(parts[79]),
    hr_windspeed_01:             parseFloat(parts[80]),
    hr_windspeed_02:             parseFloat(parts[81]),
    hr_windspeed_03:             parseFloat(parts[82]),
    hr_windspeed_04:             parseFloat(parts[83]),
    hr_windspeed_05:             parseFloat(parts[84]),
    hr_windspeed_06:             parseFloat(parts[85]),
    hr_windspeed_07:             parseFloat(parts[86]),
    hr_windspeed_08:             parseFloat(parts[87]),
    hr_windspeed_09:             parseFloat(parts[88]),
    hr_windspeed_10:             parseFloat(parts[89]),
    hr_temp_01:                  parseFloat(parts[90]),
    hr_temp_02:                  parseFloat(parts[91]),
    hr_temp_03:                  parseFloat(parts[92]),
    hr_temp_04:                  parseFloat(parts[93]),
    hr_temp_05:                  parseFloat(parts[94]),
    hr_temp_06:                  parseFloat(parts[95]),
    hr_temp_07:                  parseFloat(parts[96]),
    hr_temp_08:                  parseFloat(parts[97]),
    hr_temp_09:                  parseFloat(parts[98]),
    hr_temp_10:                  parseFloat(parts[99]),
    hr_rain_01:                  parseFloat(parts[100]),
    hr_rain_02:                  parseFloat(parts[101]),
    hr_rain_03:                  parseFloat(parts[102]),
    hr_rain_04:                  parseFloat(parts[103]),
    hr_rain_05:                  parseFloat(parts[104]),
    hr_rain_06:                  parseFloat(parts[105]),
    hr_rain_07:                  parseFloat(parts[106]),
    hr_rain_08:                  parseFloat(parts[107]),
    hr_rain_09:                  parseFloat(parts[108]),
    hr_rain_10:                  parseFloat(parts[109]),
    max_heat_index:              parseFloat(parts[110]),
    min_heat_index:              parseFloat(parts[111]),
    heat_index:                  parseFloat(parts[112]),
    max_avg_windspeed_today:     parseFloat(parts[113]),
    lightning_count_last_minute: parseInt(parts[114], 10),
    last_lightning_time:         parts[115],
    last_lightning_date:         parts[116],
    avg_wind_direction:          parseFloat(parts[117]),
    nexstorm_last_strike_distance: parseFloat(parts[118]),
    nexstorm_last_strike_bearing: parseFloat(parts[119]),
    extra_temp_sensor_7:         parseFloat(parts[120]),
    extra_temp_sensor_8:         parseFloat(parts[121]),
    extra_hum_sensor_4:          parseFloat(parts[122]),
    extra_hum_sensor_5:          parseFloat(parts[123]),
    extra_hum_sensor_6:          parseFloat(parts[124]),
    extra_hum_sensor_7:          parseFloat(parts[125]),
    extra_hum_sensor_8:          parseFloat(parts[126]),
    vp_solar_wm2:                parseFloat(parts[127]),
    max_in_temp:                 parseFloat(parts[128]),
    min_in_temp:                 parseFloat(parts[129]),
    apparent_temp:               parseFloat(parts[130]),
    max_baro:                    parseFloat(parts[131]),
    min_baro:                    parseFloat(parts[132]),
    max_gust_last_hour:          parseFloat(parts[133]),
    max_gust_last_hour_time:     parts[134],
    max_gust_today_time:         parts[135],
    max_apparent_temp:           parseFloat(parts[136]),
    min_apparent_temp:           parseFloat(parts[137]),
    max_dew_point:               parseFloat(parts[138]),
    min_dew_point:               parseFloat(parts[139]),
    max_gust_last_minute:        parseFloat(parts[140]),
    current_year:                parseInt(parts[141], 10),
    thsw_index:                  parseFloat(parts[142]),
    temp_trend:                  parseInt(parts[143], 10),
    humidity_trend:              parseInt(parts[144], 10),
    humidex_trend:               parseInt(parts[145], 10),
    hr_wind_dir_01:              parseFloat(parts[146]),
    hr_wind_dir_02:              parseFloat(parts[147]),
    hr_wind_dir_03:              parseFloat(parts[148]),
    hr_wind_dir_04:              parseFloat(parts[149]),
    hr_wind_dir_05:              parseFloat(parts[150]),
    hr_wind_dir_06:              parseFloat(parts[151]),
    hr_wind_dir_07:              parseFloat(parts[152]),
    hr_wind_dir_08:              parseFloat(parts[153]),
    hr_wind_dir_09:              parseFloat(parts[154]),
    hr_wind_dir_10:              parseFloat(parts[155]),
    leaf_wetness_vp:             parseFloat(parts[156]),
    soil_moisture_vp:            parseFloat(parts[157]),
    avg_wind_10min:              parseFloat(parts[158]),
    wet_bulb_temp:               parseFloat(parts[159]),
    latitude:                    parseFloat(parts[160]),
    longitude:                   parseFloat(parts[161]),
    rain_9am_reset:              parseFloat(parts[162]),
    daily_high_humidity:         parseFloat(parts[163]),
    daily_low_humidity:          parseFloat(parts[164]),
    rain_midnight_reset:         parseFloat(parts[165]),
    daily_low_windchill_time:    parts[166],
    cost_channel_1_watts:        parseFloat(parts[167]),
    cost_channel_2_watts:        parseFloat(parts[168]),
    cost_channel_3_watts:        parseFloat(parts[169]),
    cost_channel_4_watts:        parseFloat(parts[170]),
    cost_channel_5_watts:        parseFloat(parts[171]),
    cost_channel_6_watts:        parseFloat(parts[172]),
    daily_wind_run_km:           parseFloat(parts[173]),
    daily_max_temp_time:         parts[174],
    daily_min_temp_time:         parts[175],
    avg_wind_dir_10min:          parseFloat(parts[176]),
    firmware_version:            parts[177],
  };
}