CREATE TABLE IF NOT EXISTS weather_stats (
  `date` DATE NOT NULL PRIMARY KEY,
  `low` FLOAT NOT NULL,
  `high` FLOAT NOT NULL,
  `current` FLOAT NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;