-- server\migrations\005_create_weather_daily_max.sql
CREATE TABLE IF NOT EXISTS weather_daily_max (
  `date` DATE NOT NULL PRIMARY KEY,
  `max_out_temp` FLOAT,
  `max_in_temp` FLOAT,
  `max_soil_temp` FLOAT,
  `max_wmr968_extra_temp` FLOAT,
  `max_extra_temp_sensor_1` FLOAT,
  `max_extra_temp_sensor_2` FLOAT,
  `max_extra_temp_sensor_3` FLOAT,
  `max_extra_temp_sensor_4` FLOAT,
  `max_extra_temp_sensor_5` FLOAT,
  `max_extra_temp_sensor_6` FLOAT,
  `max_wind_chill` FLOAT,
  `max_humidex` FLOAT,
  `max_dew_point` FLOAT,
  `max_heat_index` FLOAT,
  `max_extra_temp_sensor_7` FLOAT,
  `max_extra_temp_sensor_8` FLOAT,
  `max_apparent_temp` FLOAT,
  `max_wet_bulb_temp` FLOAT,
  `max_out_hum` FLOAT,
  `max_in_hum` FLOAT,
  `max_wmr968_extra_hum` FLOAT,
  `max_extra_hum_sensor_1` FLOAT,
  `max_extra_hum_sensor_2` FLOAT,
  `max_extra_hum_sensor_3` FLOAT,
  `max_extra_hum_sensor_4` FLOAT,
  `max_extra_hum_sensor_5` FLOAT,
  `max_extra_hum_sensor_6` FLOAT,
  `max_extra_hum_sensor_7` FLOAT,
  `max_extra_hum_sensor_8` FLOAT,
  `max_average_windspeed` FLOAT,
  `max_current_windspeed` FLOAT,
  `max_avg_wind_10min` FLOAT,
  `max_barometer` FLOAT,
  `max_rain_rate_mm_min` FLOAT,
  `max_solar_percent_of_max` FLOAT,
  `max_uv_index` FLOAT,
  `max_vp_solar_wm2` FLOAT,
  `max_cloud_height` FLOAT,
  `max_leaf_wetness_vp` FLOAT,
  `max_soil_moisture_vp` FLOAT,
  `max_day_rain` FLOAT,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;