-- server\migrations\006_create_weather_daily_min.sql
CREATE TABLE IF NOT EXISTS weather_daily_min (
  `date` DATE NOT NULL PRIMARY KEY,
  `min_out_temp` FLOAT,
  `min_in_temp` FLOAT,
  `min_soil_temp` FLOAT,
  `min_wmr968_extra_temp` FLOAT,
  `min_extra_temp_sensor_1` FLOAT,
  `min_extra_temp_sensor_2` FLOAT,
  `min_extra_temp_sensor_3` FLOAT,
  `min_extra_temp_sensor_4` FLOAT,
  `min_extra_temp_sensor_5` FLOAT,
  `min_extra_temp_sensor_6` FLOAT,
  `min_wind_chill` FLOAT,
  `min_humidex` FLOAT,
  `min_dew_point` FLOAT,
  `min_heat_index` FLOAT,
  `min_extra_temp_sensor_7` FLOAT,
  `min_extra_temp_sensor_8` FLOAT,
  `min_apparent_temp` FLOAT,
  `min_wet_bulb_temp` FLOAT,
  `min_out_hum` FLOAT,
  `min_in_hum` FLOAT,
  `min_wmr968_extra_hum` FLOAT,
  `min_extra_hum_sensor_1` FLOAT,
  `min_extra_hum_sensor_2` FLOAT,
  `min_extra_hum_sensor_3` FLOAT,
  `min_extra_hum_sensor_4` FLOAT,
  `min_extra_hum_sensor_5` FLOAT,
  `min_extra_hum_sensor_6` FLOAT,
  `min_extra_hum_sensor_7` FLOAT,
  `min_extra_hum_sensor_8` FLOAT,
  `min_average_windspeed` FLOAT,
  `min_current_windspeed` FLOAT,
  `min_avg_wind_10min` FLOAT,
  `min_barometer` FLOAT,
  `min_rain_rate_mm_min` FLOAT,
  `min_solar_percent_of_max` FLOAT,
  `min_uv_index` FLOAT,
  `min_vp_solar_wm2` FLOAT,
  `min_cloud_height` FLOAT,
  `min_leaf_wetness_vp` FLOAT,
  `min_soil_moisture_vp` FLOAT,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;