-- server\migrations\007_create_weather_daily_avg.sql
CREATE TABLE IF NOT EXISTS weather_daily_avg (
  `date` DATE NOT NULL PRIMARY KEY,
  `avg_out_temp` FLOAT,
  `avg_in_temp` FLOAT,
  `avg_soil_temp` FLOAT,
  `avg_wmr968_extra_temp` FLOAT,
  `avg_extra_temp_sensor_1` FLOAT,
  `avg_extra_temp_sensor_2` FLOAT,
  `avg_extra_temp_sensor_3` FLOAT,
  `avg_extra_temp_sensor_4` FLOAT,
  `avg_extra_temp_sensor_5` FLOAT,
  `avg_extra_temp_sensor_6` FLOAT,
  `avg_wind_chill` FLOAT,
  `avg_humidex` FLOAT,
  `avg_dew_point` FLOAT,
  `avg_heat_index` FLOAT,
  `avg_extra_temp_sensor_7` FLOAT,
  `avg_extra_temp_sensor_8` FLOAT,
  `avg_apparent_temp` FLOAT,
  `avg_wet_bulb_temp` FLOAT,
  `avg_out_hum` FLOAT,
  `avg_in_hum` FLOAT,
  `avg_wmr968_extra_hum` FLOAT,
  `avg_extra_hum_sensor_1` FLOAT,
  `avg_extra_hum_sensor_2` FLOAT,
  `avg_extra_hum_sensor_3` FLOAT,
  `avg_extra_hum_sensor_4` FLOAT,
  `avg_extra_hum_sensor_5` FLOAT,
  `avg_extra_hum_sensor_6` FLOAT,
  `avg_extra_hum_sensor_7` FLOAT,
  `avg_extra_hum_sensor_8` FLOAT,
  `avg_average_windspeed` FLOAT,
  `avg_current_windspeed` FLOAT,
  `avg_avg_wind_10min` FLOAT,
  `avg_barometer` FLOAT,
  `avg_rain_rate_mm_min` FLOAT,
  `avg_solar_percent_of_max` FLOAT,
  `avg_uv_index` FLOAT,
  `avg_vp_solar_wm2` FLOAT,
  `avg_cloud_height` FLOAT,
  `avg_leaf_wetness_vp` FLOAT,
  `avg_soil_moisture_vp` FLOAT,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;