-- Enable event scheduler if not already
SET GLOBAL event_scheduler = ON;

-- Create the event
DELIMITER $$

CREATE EVENT IF NOT EXISTS daily_weather_wipe
ON SCHEDULE EVERY 1 DAY
STARTS '2025-07-22 00:00:00'  -- Adjust start date if needed
DO
BEGIN
  DECLARE yesterday DATE;
  SET yesterday = CURDATE() - INTERVAL 1 DAY;

  -- Insert max values for yesterday
  INSERT INTO weather_daily_max (
    `date`,
    `max_station_id`,
    `max_average_windspeed`,
    `max_current_windspeed`,
    `max_wind_dir`,
    `max_out_temp`,
    `max_out_hum`,
    `max_barometer`,
    `max_day_rain`,
    `max_month_rain`,
    `max_year_rain`,
    `max_rain_rate_mm_min`,
    `max_rain_rate_max_mm_min`,
    `max_in_temp`,
    `max_in_hum`,
    `max_soil_temp`,
    `max_forecast_icon_code`,
    `max_wmr968_extra_temp`,
    `max_wmr968_extra_hum`,
    `max_wmr968_extra_sensor`,
    `max_yesterday_rain`,
    `max_extra_temp_sensor_1`,
    `max_extra_temp_sensor_2`,
    `max_extra_temp_sensor_3`,
    `max_extra_temp_sensor_4`,
    `max_extra_temp_sensor_5`,
    `max_extra_temp_sensor_6`,
    `max_extra_hum_sensor_1`,
    `max_extra_hum_sensor_2`,
    `max_extra_hum_sensor_3`,
    `max_measurement_hour`,
    `max_measurement_minute`,
    `max_measurement_second`,
    `max_location_label`,
    `max_lightning_count_since_noon`,
    `max_solar_percent_of_max`,
    `max_measurement_day`,
    `max_measurement_month`,
    `max_wmr968_batt1`,
    `max_wmr968_batt2`,
    `max_wmr968_batt3`,
    `max_wmr968_batt4`,
    `max_wmr968_batt5`,
    `max_wmr968_batt6`,
    `max_wmr968_batt7`,
    `max_wind_chill`,
    `max_humidex`,
    `max_max_temp_today`,
    `max_min_temp_today`,
    `max_current_condition_icon`,
    `max_sky_condition_text`,
    `max_baro_trend_last_hour`,
    `max_windspeed_hour_01`,
    `max_windspeed_hour_02`,
    `max_windspeed_hour_03`,
    `max_windspeed_hour_04`,
    `max_windspeed_hour_05`,
    `max_windspeed_hour_06`,
    `max_windspeed_hour_07`,
    `max_windspeed_hour_08`,
    `max_windspeed_hour_09`,
    `max_windspeed_hour_10`,
    `max_windspeed_hour_11`,
    `max_windspeed_hour_12`,
    `max_windspeed_hour_13`,
    `max_windspeed_hour_14`,
    `max_windspeed_hour_15`,
    `max_windspeed_hour_16`,
    `max_windspeed_hour_17`,
    `max_windspeed_hour_18`,
    `max_windspeed_hour_19`,
    `max_windspeed_hour_20`,
    `max_max_wind_gust`,
    `max_dew_point`,
    `max_cloud_height`,
    `max_current_date`,
    `max_max_humidex`,
    `max_min_humidex`,
    `max_max_windchill`,
    `max_min_windchill`,
    `max_uv_index`,
    `max_hr_windspeed_01`,
    `max_hr_windspeed_02`,
    `max_hr_windspeed_03`,
    `max_hr_windspeed_04`,
    `max_hr_windspeed_05`,
    `max_hr_windspeed_06`,
    `max_hr_windspeed_07`,
    `max_hr_windspeed_08`,
    `max_hr_windspeed_09`,
    `max_hr_windspeed_10`,
    `max_hr_temp_01`,
    `max_hr_temp_02`,
    `max_hr_temp_03`,
    `max_hr_temp_04`,
    `max_hr_temp_05`,
    `max_hr_temp_06`,
    `max_hr_temp_07`,
    `max_hr_temp_08`,
    `max_hr_temp_09`,
    `max_hr_temp_10`,
    `max_hr_rain_01`,
    `max_hr_rain_02`,
    `max_hr_rain_03`,
    `max_hr_rain_04`,
    `max_hr_rain_05`,
    `max_hr_rain_06`,
    `max_hr_rain_07`,
    `max_hr_rain_08`,
    `max_hr_rain_09`,
    `max_hr_rain_10`,
    `max_max_heat_index`,
    `max_min_heat_index`,
    `max_heat_index`,
    `max_max_avg_windspeed_today`,
    `max_lightning_count_last_minute`,
    `max_last_lightning_time`,
    `max_last_lightning_date`,
    `max_avg_wind_direction`,
    `max_nexstorm_last_strike_distance`,
    `max_nexstorm_last_strike_bearing`,
    `max_extra_temp_sensor_7`,
    `max_extra_temp_sensor_8`,
    `max_extra_hum_sensor_4`,
    `max_extra_hum_sensor_5`,
    `max_extra_hum_sensor_6`,
    `max_extra_hum_sensor_7`,
    `max_extra_hum_sensor_8`,
    `max_vp_solar_wm2`,
    `max_max_in_temp`,
    `max_min_in_temp`,
    `max_apparent_temp`,
    `max_max_baro`,
    `max_min_baro`,
    `max_max_gust_last_hour`,
    `max_max_gust_last_hour_time`,
    `max_max_gust_today_time`,
    `max_max_apparent_temp`,
    `max_min_apparent_temp`,
    `max_max_dew_point`,
    `max_min_dew_point`,
    `max_max_gust_last_minute`,
    `max_current_year`,
    `max_thsw_index`,
    `max_temp_trend`,
    `max_humidity_trend`,
    `max_humidex_trend`,
    `max_hr_wind_dir_01`,
    `max_hr_wind_dir_02`,
    `max_hr_wind_dir_03`,
    `max_hr_wind_dir_04`,
    `max_hr_wind_dir_05`,
    `max_hr_wind_dir_06`,
    `max_hr_wind_dir_07`,
    `max_hr_wind_dir_08`,
    `max_hr_wind_dir_09`,
    `max_hr_wind_dir_10`,
    `max_leaf_wetness_vp`,
    `max_soil_moisture_vp`,
    `max_avg_wind_10min`,
    `max_wet_bulb_temp`,
    `max_latitude`,
    `max_longitude`,
    `max_rain_9am_reset`,
    `max_daily_high_humidity`,
    `max_daily_low_humidity`,
    `max_rain_midnight_reset`,
    `max_daily_low_windchill_time`,
    `max_cost_channel_1_watts`,
    `max_cost_channel_2_watts`,
    `max_cost_channel_3_watts`,
    `max_cost_channel_4_watts`,
    `max_cost_channel_5_watts`,
    `max_cost_channel_6_watts`,
    `max_daily_wind_run_km`,
    `max_daily_max_temp_time`,
    `max_daily_min_temp_time`,
    `max_avg_wind_dir_10min`,
    `max_firmware_version`
  ) SELECT
    yesterday,
    MAX(station_id),
    MAX(average_windspeed),
    MAX(current_windspeed),
    MAX(wind_dir),
    MAX(out_temp),
    MAX(out_hum),
    MAX(barometer),
    MAX(day_rain),
    MAX(month_rain),
    MAX(year_rain),
    MAX(rain_rate_mm_min),
    MAX(rain_rate_max_mm_min),
    MAX(in_temp),
    MAX(in_hum),
    MAX(soil_temp),
    MAX(forecast_icon_code),
    MAX(wmr968_extra_temp),
    MAX(wmr968_extra_hum),
    MAX(wmr968_extra_sensor),
    MAX(yesterday_rain),
    MAX(extra_temp_sensor_1),
    MAX(extra_temp_sensor_2),
    MAX(extra_temp_sensor_3),
    MAX(extra_temp_sensor_4),
    MAX(extra_temp_sensor_5),
    MAX(extra_temp_sensor_6),
    MAX(extra_hum_sensor_1),
    MAX(extra_hum_sensor_2),
    MAX(extra_hum_sensor_3),
    MAX(measurement_hour),
    MAX(measurement_minute),
    MAX(measurement_second),
    MAX(location_label),
    MAX(lightning_count_since_noon),
    MAX(solar_percent_of_max),
    MAX(measurement_day),
    MAX(measurement_month),
    MAX(wmr968_batt1),
    MAX(wmr968_batt2),
    MAX(wmr968_batt3),
    MAX(wmr968_batt4),
    MAX(wmr968_batt5),
    MAX(wmr968_batt6),
    MAX(wmr968_batt7),
    MAX(wind_chill),
    MAX(humidex),
    MAX(max_temp_today),
    MAX(min_temp_today),
    MAX(current_condition_icon),
    MAX(sky_condition_text),
    MAX(baro_trend_last_hour),
    MAX(windspeed_hour_01),
    MAX(windspeed_hour_02),
    MAX(windspeed_hour_03),
    MAX(windspeed_hour_04),
    MAX(windspeed_hour_05),
    MAX(windspeed_hour_06),
    MAX(windspeed_hour_07),
    MAX(windspeed_hour_08),
    MAX(windspeed_hour_09),
    MAX(windspeed_hour_10),
    MAX(windspeed_hour_11),
    MAX(windspeed_hour_12),
    MAX(windspeed_hour_13),
    MAX(windspeed_hour_14),
    MAX(windspeed_hour_15),
    MAX(windspeed_hour_16),
    MAX(windspeed_hour_17),
    MAX(windspeed_hour_18),
    MAX(windspeed_hour_19),
    MAX(windspeed_hour_20),
    MAX(max_wind_gust),
    MAX(dew_point),
    MAX(cloud_height),
    MAX(current_date),
    MAX(max_humidex),
    MAX(min_humidex),
    MAX(max_windchill),
    MAX(min_windchill),
    MAX(uv_index),
    MAX(hr_windspeed_01),
    MAX(hr_windspeed_02),
    MAX(hr_windspeed_03),
    MAX(hr_windspeed_04),
    MAX(hr_windspeed_05),
    MAX(hr_windspeed_06),
    MAX(hr_windspeed_07),
    MAX(hr_windspeed_08),
    MAX(hr_windspeed_09),
    MAX(hr_windspeed_10),
    MAX(hr_temp_01),
    MAX(hr_temp_02),
    MAX(hr_temp_03),
    MAX(hr_temp_04),
    MAX(hr_temp_05),
    MAX(hr_temp_06),
    MAX(hr_temp_07),
    MAX(hr_temp_08),
    MAX(hr_temp_09),
    MAX(hr_temp_10),
    MAX(hr_rain_01),
    MAX(hr_rain_02),
    MAX(hr_rain_03),
    MAX(hr_rain_04),
    MAX(hr_rain_05),
    MAX(hr_rain_06),
    MAX(hr_rain_07),
    MAX(hr_rain_08),
    MAX(hr_rain_09),
    MAX(hr_rain_10),
    MAX(max_heat_index),
    MAX(min_heat_index),
    MAX(heat_index),
    MAX(max_avg_windspeed_today),
    MAX(lightning_count_last_minute),
    MAX(last_lightning_time),
    MAX(last_lightning_date),
    MAX(avg_wind_direction),
    MAX(nexstorm_last_strike_distance),
    MAX(nexstorm_last_strike_bearing),
    MAX(extra_temp_sensor_7),
    MAX(extra_temp_sensor_8),
    MAX(extra_hum_sensor_4),
    MAX(extra_hum_sensor_5),
    MAX(extra_hum_sensor_6),
    MAX(extra_hum_sensor_7),
    MAX(extra_hum_sensor_8),
    MAX(vp_solar_wm2),
    MAX(max_in_temp),
    MAX(min_in_temp),
    MAX(apparent_temp),
    MAX(max_baro),
    MAX(min_baro),
    MAX(max_gust_last_hour),
    MAX(max_gust_last_hour_time),
    MAX(max_gust_today_time),
    MAX(max_apparent_temp),
    MAX(min_apparent_temp),
    MAX(max_dew_point),
    MAX(min_dew_point),
    MAX(max_gust_last_minute),
    MAX(current_year),
    MAX(thsw_index),
    MAX(temp_trend),
    MAX(humidity_trend),
    MAX(humidex_trend),
    MAX(hr_wind_dir_01),
    MAX(hr_wind_dir_02),
    MAX(hr_wind_dir_03),
    MAX(hr_wind_dir_04),
    MAX(hr_wind_dir_05),
    MAX(hr_wind_dir_06),
    MAX(hr_wind_dir_07),
    MAX(hr_wind_dir_08),
    MAX(hr_wind_dir_09),
    MAX(hr_wind_dir_10),
    MAX(leaf_wetness_vp),
    MAX(soil_moisture_vp),
    MAX(avg_wind_10min),
    MAX(wet_bulb_temp),
    MAX(latitude),
    MAX(longitude),
    MAX(rain_9am_reset),
    MAX(daily_high_humidity),
    MAX(daily_low_humidity),
    MAX(rain_midnight_reset),
    MAX(daily_low_windchill_time),
    MAX(cost_channel_1_watts),
    MAX(cost_channel_2_watts),
    MAX(cost_channel_3_watts),
    MAX(cost_channel_4_watts),
    MAX(cost_channel_5_watts),
    MAX(cost_channel_6_watts),
    MAX(daily_wind_run_km),
    MAX(daily_max_temp_time),
    MAX(daily_min_temp_time),
    MAX(avg_wind_dir_10min),
    MAX(firmware_version)
  FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) = yesterday
  ON DUPLICATE KEY UPDATE
    max_station_id = VALUES(max_station_id),
    max_average_windspeed = VALUES(max_average_windspeed),
    max_current_windspeed = VALUES(max_current_windspeed),
    max_wind_dir = VALUES(max_wind_dir),
    max_out_temp = VALUES(max_out_temp),
    max_out_hum = VALUES(max_out_hum),
    max_barometer = VALUES(max_barometer),
    max_day_rain = VALUES(max_day_rain),
    max_month_rain = VALUES(max_month_rain),
    max_year_rain = VALUES(max_year_rain),
    max_rain_rate_mm_min = VALUES(max_rain_rate_mm_min),
    max_rain_rate_max_mm_min = VALUES(max_rain_rate_max_mm_min),
    max_in_temp = VALUES(max_in_temp),
    max_in_hum = VALUES(max_in_hum),
    max_soil_temp = VALUES(max_soil_temp),
    max_forecast_icon_code = VALUES(max_forecast_icon_code),
    max_wmr968_extra_temp = VALUES(max_wmr968_extra_temp),
    max_wmr968_extra_hum = VALUES(max_wmr968_extra_hum),
    max_wmr968_extra_sensor = VALUES(max_wmr968_extra_sensor),
    max_yesterday_rain = VALUES(max_yesterday_rain),
    max_extra_temp_sensor_1 = VALUES(max_extra_temp_sensor_1),
    max_extra_temp_sensor_2 = VALUES(max_extra_temp_sensor_2),
    max_extra_temp_sensor_3 = VALUES(max_extra_temp_sensor_3),
    max_extra_temp_sensor_4 = VALUES(max_extra_temp_sensor_4),
    max_extra_temp_sensor_5 = VALUES(max_extra_temp_sensor_5),
    max_extra_temp_sensor_6 = VALUES(max_extra_temp_sensor_6),
    max_extra_hum_sensor_1 = VALUES(max_extra_hum_sensor_1),
    max_extra_hum_sensor_2 = VALUES(max_extra_hum_sensor_2),
    max_extra_hum_sensor_3 = VALUES(max_extra_hum_sensor_3),
    max_measurement_hour = VALUES(max_measurement_hour),
    max_measurement_minute = VALUES(max_measurement_minute),
    max_measurement_second = VALUES(max_measurement_second),
    max_location_label = VALUES(max_location_label),
    max_lightning_count_since_noon = VALUES(max_lightning_count_since_noon),
    max_solar_percent_of_max = VALUES(max_solar_percent_of_max),
    max_measurement_day = VALUES(max_measurement_day),
    max_measurement_month = VALUES(max_measurement_month),
    max_wmr968_batt1 = VALUES(max_wmr968_batt1),
    max_wmr968_batt2 = VALUES(max_wmr968_batt2),
    max_wmr968_batt3 = VALUES(max_wmr968_batt3),
    max_wmr968_batt4 = VALUES(max_wmr968_batt4),
    max_wmr968_batt5 = VALUES(max_wmr968_batt5),
    max_wmr968_batt6 = VALUES(max_wmr968_batt6),
    max_wmr968_batt7 = VALUES(max_wmr968_batt7),
    max_wind_chill = VALUES(max_wind_chill),
    max_humidex = VALUES(max_humidex),
    max_max_temp_today = VALUES(max_max_temp_today),
    max_min_temp_today = VALUES(max_min_temp_today),
    max_current_condition_icon = VALUES(max_current_condition_icon),
    max_sky_condition_text = VALUES(max_sky_condition_text),
    max_baro_trend_last_hour = VALUES(max_baro_trend_last_hour),
    max_windspeed_hour_01 = VALUES(max_windspeed_hour_01),
    max_windspeed_hour_02 = VALUES(max_windspeed_hour_02),
    max_windspeed_hour_03 = VALUES(max_windspeed_hour_03),
    max_windspeed_hour_04 = VALUES(max_windspeed_hour_04),
    max_windspeed_hour_05 = VALUES(max_windspeed_hour_05),
    max_windspeed_hour_06 = VALUES(max_windspeed_hour_06),
    max_windspeed_hour_07 = VALUES(max_windspeed_hour_07),
    max_windspeed_hour_08 = VALUES(max_windspeed_hour_08),
    max_windspeed_hour_09 = VALUES(max_windspeed_hour_09),
    max_windspeed_hour_10 = VALUES(max_windspeed_hour_10),
    max_windspeed_hour_11 = VALUES(max_windspeed_hour_11),
    max_windspeed_hour_12 = VALUES(max_windspeed_hour_12),
    max_windspeed_hour_13 = VALUES(max_windspeed_hour_13),
    max_windspeed_hour_14 = VALUES(max_windspeed_hour_14),
    max_windspeed_hour_15 = VALUES(max_windspeed_hour_15),
    max_windspeed_hour_16 = VALUES(max_windspeed_hour_16),
    max_windspeed_hour_17 = VALUES(max_windspeed_hour_17),
    max_windspeed_hour_18 = VALUES(max_windspeed_hour_18),
    max_windspeed_hour_19 = VALUES(max_windspeed_hour_19),
    max_windspeed_hour_20 = VALUES(max_windspeed_hour_20),
    max_max_wind_gust = VALUES(max_max_wind_gust),
    max_dew_point = VALUES(max_dew_point),
    max_cloud_height = VALUES(max_cloud_height),
    max_current_date = VALUES(max_current_date),
    max_max_humidex = VALUES(max_max_humidex),
    max_min_humidex = VALUES(max_min_humidex),
    max_max_windchill = VALUES(max_max_windchill),
    max_min_windchill = VALUES(max_min_windchill),
    max_uv_index = VALUES(max_uv_index),
    max_hr_windspeed_01 = VALUES(max_hr_windspeed_01),
    max_hr_windspeed_02 = VALUES(max_hr_windspeed_02),
    max_hr_windspeed_03 = VALUES(max_hr_windspeed_03),
    max_hr_windspeed_04 = VALUES(max_hr_windspeed_04),
    max_hr_windspeed_05 = VALUES(max_hr_windspeed_05),
    max_hr_windspeed_06 = VALUES(max_hr_windspeed_06),
    max_hr_windspeed_07 = VALUES(max_hr_windspeed_07),
    max_hr_windspeed_08 = VALUES(max_hr_windspeed_08),
    max_hr_windspeed_09 = VALUES(max_hr_windspeed_09),
    max_hr_windspeed_10 = VALUES(max_hr_windspeed_10),
    max_hr_temp_01 = VALUES(max_hr_temp_01),
    max_hr_temp_02 = VALUES(max_hr_temp_02),
    max_hr_temp_03 = VALUES(max_hr_temp_03),
    max_hr_temp_04 = VALUES(max_hr_temp_04),
    max_hr_temp_05 = VALUES(max_hr_temp_05),
    max_hr_temp_06 = VALUES(max_hr_temp_06),
    max_hr_temp_07 = VALUES(max_hr_temp_07),
    max_hr_temp_08 = VALUES(max_hr_temp_08),
    max_hr_temp_09 = VALUES(max_hr_temp_09),
    max_hr_temp_10 = VALUES(max_hr_temp_10),
    max_hr_rain_01 = VALUES(max_hr_rain_01),
    max_hr_rain_02 = VALUES(max_hr_rain_02),
    max_hr_rain_03 = VALUES(max_hr_rain_03),
    max_hr_rain_04 = VALUES(max_hr_rain_04),
    max_hr_rain_05 = VALUES(max_hr_rain_05),
    max_hr_rain_06 = VALUES(max_hr_rain_06),
    max_hr_rain_07 = VALUES(max_hr_rain_07),
    max_hr_rain_08 = VALUES(max_hr_rain_08),
    max_hr_rain_09 = VALUES(max_hr_rain_09),
    max_hr_rain_10 = VALUES(max_hr_rain_10),
    max_max_heat_index = VALUES(max_max_heat_index),
    max_min_heat_index = VALUES(max_min_heat_index),
    max_heat_index = VALUES(max_heat_index),
    max_max_avg_windspeed_today = VALUES(max_max_avg_windspeed_today),
    max_lightning_count_last_minute = VALUES(max_lightning_count_last_minute),
    max_last_lightning_time = VALUES(max_last_lightning_time),
    max_last_lightning_date = VALUES(max_last_lightning_date),
    max_avg_wind_direction = VALUES(max_avg_wind_direction),
    max_nexstorm_last_strike_distance = VALUES(max_nexstorm_last_strike_distance),
    max_nexstorm_last_strike_bearing = VALUES(max_nexstorm_last_strike_bearing),
    max_extra_temp_sensor_7 = VALUES(max_extra_temp_sensor_7),
    max_extra_temp_sensor_8 = VALUES(max_extra_temp_sensor_8),
    max_extra_hum_sensor_4 = VALUES(max_extra_hum_sensor_4),
    max_extra_hum_sensor_5 = VALUES(max_extra_hum_sensor_5),
    max_extra_hum_sensor_6 = VALUES(max_extra_hum_sensor_6),
    max_extra_hum_sensor_7 = VALUES(max_extra_hum_sensor_7),
    max_extra_hum_sensor_8 = VALUES(max_extra_hum_sensor_8),
    max_vp_solar_wm2 = VALUES(max_vp_solar_wm2),
    max_max_in_temp = VALUES(max_max_in_temp),
    max_min_in_temp = VALUES(max_min_in_temp),
    max_apparent_temp = VALUES(max_apparent_temp),
    max_max_baro = VALUES(max_max_baro),
    max_min_baro = VALUES(max_min_baro),
    max_max_gust_last_hour = VALUES(max_max_gust_last_hour),
    max_max_gust_last_hour_time = VALUES(max_max_gust_last_hour_time),
    max_max_gust_today_time = VALUES(max_max_gust_today_time),
    max_max_apparent_temp = VALUES(max_max_apparent_temp),
    max_min_apparent_temp = VALUES(max_min_apparent_temp),
    max_max_dew_point = VALUES(max_max_dew_point),
    max_min_dew_point = VALUES(max_min_dew_point),
    max_max_gust_last_minute = VALUES(max_max_gust_last_minute),
    max_current_year = VALUES(max_current_year),
    max_thsw_index = VALUES(max_thsw_index),
    max_temp_trend = VALUES(max_temp_trend),
    max_humidity_trend = VALUES(max_humidity_trend),
    max_humidex_trend = VALUES(max_humidex_trend),
    max_hr_wind_dir_01 = VALUES(max_hr_wind_dir_01),
    max_hr_wind_dir_02 = VALUES(max_hr_wind_dir_02),
    max_hr_wind_dir_03 = VALUES(max_hr_wind_dir_03),
    max_hr_wind_dir_04 = VALUES(max_hr_wind_dir_04),
    max_hr_wind_dir_05 = VALUES(max_hr_wind_dir_05),
    max_hr_wind_dir_06 = VALUES(max_hr_wind_dir_06),
    max_hr_wind_dir_07 = VALUES(max_hr_wind_dir_07),
    max_hr_wind_dir_08 = VALUES(max_hr_wind_dir_08),
    max_hr_wind_dir_09 = VALUES(max_hr_wind_dir_09),
    max_hr_wind_dir_10 = VALUES(max_hr_wind_dir_10),
    max_leaf_wetness_vp = VALUES(max_leaf_wetness_vp),
    max_soil_moisture_vp = VALUES(max_soil_moisture_vp),
    max_avg_wind_10min = VALUES(max_avg_wind_10min),
    max_wet_bulb_temp = VALUES(max_wet_bulb_temp),
    max_latitude = VALUES(max_latitude),
    max_longitude = VALUES(max_longitude),
    max_rain_9am_reset = VALUES(max_rain_9am_reset),
    max_daily_high_humidity = VALUES(max_daily_high_humidity),
    max_daily_low_humidity = VALUES(max_daily_low_humidity),
    max_rain_midnight_reset = VALUES(max_rain_midnight_reset),
    max_daily_low_windchill_time = VALUES(max_daily_low_windchill_time),
    max_cost_channel_1_watts = VALUES(max_cost_channel_1_watts),
    max_cost_channel_2_watts = VALUES(max_cost_channel_2_watts),
    max_cost_channel_3_watts = VALUES(max_cost_channel_3_watts),
    max_cost_channel_4_watts = VALUES(max_cost_channel_4_watts),
    max_cost_channel_5_watts = VALUES(max_cost_channel_5_watts),
    max_cost_channel_6_watts = VALUES(max_cost_channel_6_watts),
    max_daily_wind_run_km = VALUES(max_daily_wind_run_km),
    max_daily_max_temp_time = VALUES(max_daily_max_temp_time),
    max_daily_min_temp_time = VALUES(max_daily_min_temp_time),
    max_avg_wind_dir_10min = VALUES(max_avg_wind_dir_10min),
    max_firmware_version = VALUES(max_firmware_version);

  -- Wipe old readings
  DELETE FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) < CURDATE();
END $$

DELIMITER ;