DROP PROCEDURE IF EXISTS daily_wipe;

CREATE PROCEDURE daily_wipe()
BEGIN
  DECLARE yesterday DATE;
  SET yesterday = CURDATE() - INTERVAL 1 DAY;

  -- Insert max values
  INSERT INTO weather_daily_max (
    `date`,
    `max_out_temp`,
    `max_in_temp`,
    `max_soil_temp`,
    `max_wmr968_extra_temp`,
    `max_extra_temp_sensor_1`,
    `max_extra_temp_sensor_2`,
    `max_extra_temp_sensor_3`,
    `max_extra_temp_sensor_4`,
    `max_extra_temp_sensor_5`,
    `max_extra_temp_sensor_6`,
    `max_wind_chill`,
    `max_humidex`,
    `max_dew_point`,
    `max_heat_index`,
    `max_extra_temp_sensor_7`,
    `max_extra_temp_sensor_8`,
    `max_apparent_temp`,
    `max_wet_bulb_temp`,
    `max_out_hum`,
    `max_in_hum`,
    `max_wmr968_extra_hum`,
    `max_extra_hum_sensor_1`,
    `max_extra_hum_sensor_2`,
    `max_extra_hum_sensor_3`,
    `max_extra_hum_sensor_4`,
    `max_extra_hum_sensor_5`,
    `max_extra_hum_sensor_6`,
    `max_extra_hum_sensor_7`,
    `max_extra_hum_sensor_8`,
    `max_average_windspeed`,
    `max_current_windspeed`,
    `max_avg_wind_10min`,
    `max_barometer`,
    `max_rain_rate_mm_min`,
    `max_solar_percent_of_max`,
    `max_uv_index`,
    `max_vp_solar_wm2`,
    `max_cloud_height`,
    `max_leaf_wetness_vp`,
    `max_soil_moisture_vp`,
    `max_day_rain`
  ) SELECT
    yesterday,
    COALESCE(MAX(out_temp), 0),
    COALESCE(MAX(in_temp), 0),
    COALESCE(MAX(soil_temp), 0),
    COALESCE(MAX(wmr968_extra_temp), 0),
    COALESCE(MAX(extra_temp_sensor_1), 0),
    COALESCE(MAX(extra_temp_sensor_2), 0),
    COALESCE(MAX(extra_temp_sensor_3), 0),
    COALESCE(MAX(extra_temp_sensor_4), 0),
    COALESCE(MAX(extra_temp_sensor_5), 0),
    COALESCE(MAX(extra_temp_sensor_6), 0),
    COALESCE(MAX(wind_chill), 0),
    COALESCE(MAX(humidex), 0),
    COALESCE(MAX(dew_point), 0),
    COALESCE(MAX(heat_index), 0),
    COALESCE(MAX(extra_temp_sensor_7), 0),
    COALESCE(MAX(extra_temp_sensor_8), 0),
    COALESCE(MAX(apparent_temp), 0),
    COALESCE(MAX(wet_bulb_temp), 0),
    COALESCE(MAX(out_hum), 0),
    COALESCE(MAX(in_hum), 0),
    COALESCE(MAX(wmr968_extra_hum), 0),
    COALESCE(MAX(extra_hum_sensor_1), 0),
    COALESCE(MAX(extra_hum_sensor_2), 0),
    COALESCE(MAX(extra_hum_sensor_3), 0),
    COALESCE(MAX(extra_hum_sensor_4), 0),
    COALESCE(MAX(extra_hum_sensor_5), 0),
    COALESCE(MAX(extra_hum_sensor_6), 0),
    COALESCE(MAX(extra_hum_sensor_7), 0),
    COALESCE(MAX(extra_hum_sensor_8), 0),
    COALESCE(MAX(average_windspeed), 0),
    COALESCE(MAX(current_windspeed), 0),
    COALESCE(MAX(avg_wind_10min), 0),
    COALESCE(MAX(barometer), 0),
    COALESCE(MAX(rain_rate_mm_min), 0),
    COALESCE(MAX(solar_percent_of_max), 0),
    COALESCE(MAX(uv_index), 0),
    COALESCE(MAX(vp_solar_wm2), 0),
    COALESCE(MAX(cloud_height), 0),
    COALESCE(MAX(leaf_wetness_vp), 0),
    COALESCE(MAX(soil_moisture_vp), 0),
    COALESCE(MAX(day_rain), 0)
  FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) = yesterday
  ON DUPLICATE KEY UPDATE
    max_out_temp = VALUES(max_out_temp),
    max_in_temp = VALUES(max_in_temp),
    max_soil_temp = VALUES(max_soil_temp),
    max_wmr968_extra_temp = VALUES(max_wmr968_extra_temp),
    max_extra_temp_sensor_1 = VALUES(max_extra_temp_sensor_1),
    max_extra_temp_sensor_2 = VALUES(max_extra_temp_sensor_2),
    max_extra_temp_sensor_3 = VALUES(max_extra_temp_sensor_3),
    max_extra_temp_sensor_4 = VALUES(max_extra_temp_sensor_4),
    max_extra_temp_sensor_5 = VALUES(max_extra_temp_sensor_5),
    max_extra_temp_sensor_6 = VALUES(max_extra_temp_sensor_6),
    max_wind_chill = VALUES(max_wind_chill),
    max_humidex = VALUES(max_humidex),
    max_dew_point = VALUES(max_dew_point),
    max_heat_index = VALUES(max_heat_index),
    max_extra_temp_sensor_7 = VALUES(max_extra_temp_sensor_7),
    max_extra_temp_sensor_8 = VALUES(max_extra_temp_sensor_8),
    max_apparent_temp = VALUES(max_apparent_temp),
    max_wet_bulb_temp = VALUES(max_wet_bulb_temp),
    max_out_hum = VALUES(max_out_hum),
    max_in_hum = VALUES(max_in_hum),
    max_wmr968_extra_hum = VALUES(max_wmr968_extra_hum),
    max_extra_hum_sensor_1 = VALUES(max_extra_hum_sensor_1),
    max_extra_hum_sensor_2 = VALUES(max_extra_hum_sensor_2),
    max_extra_hum_sensor_3 = VALUES(max_extra_hum_sensor_3),
    max_extra_hum_sensor_4 = VALUES(max_extra_hum_sensor_4),
    max_extra_hum_sensor_5 = VALUES(max_extra_hum_sensor_5),
    max_extra_hum_sensor_6 = VALUES(max_extra_hum_sensor_6),
    max_extra_hum_sensor_7 = VALUES(max_extra_hum_sensor_7),
    max_extra_hum_sensor_8 = VALUES(max_extra_hum_sensor_8),
    max_average_windspeed = VALUES(max_average_windspeed),
    max_current_windspeed = VALUES(max_current_windspeed),
    max_avg_wind_10min = VALUES(max_avg_wind_10min),
    max_barometer = VALUES(max_barometer),
    max_rain_rate_mm_min = VALUES(max_rain_rate_mm_min),
    max_solar_percent_of_max = VALUES(max_solar_percent_of_max),
    max_uv_index = VALUES(max_uv_index),
    max_vp_solar_wm2 = VALUES(max_vp_solar_wm2),
    max_cloud_height = VALUES(max_cloud_height),
    max_leaf_wetness_vp = VALUES(max_leaf_wetness_vp),
    max_soil_moisture_vp = VALUES(max_soil_moisture_vp),
    max_day_rain = VALUES(max_day_rain);

  -- Insert min values
  INSERT INTO weather_daily_min (
    `date`,
    `min_out_temp`,
    `min_in_temp`,
    `min_soil_temp`,
    `min_wmr968_extra_temp`,
    `min_extra_temp_sensor_1`,
    `min_extra_temp_sensor_2`,
    `min_extra_temp_sensor_3`,
    `min_extra_temp_sensor_4`,
    `min_extra_temp_sensor_5`,
    `min_extra_temp_sensor_6`,
    `min_wind_chill`,
    `min_humidex`,
    `min_dew_point`,
    `min_heat_index`,
    `min_extra_temp_sensor_7`,
    `min_extra_temp_sensor_8`,
    `min_apparent_temp`,
    `min_wet_bulb_temp`,
    `min_out_hum`,
    `min_in_hum`,
    `min_wmr968_extra_hum`,
    `min_extra_hum_sensor_1`,
    `min_extra_hum_sensor_2`,
    `min_extra_hum_sensor_3`,
    `min_extra_hum_sensor_4`,
    `min_extra_hum_sensor_5`,
    `min_extra_hum_sensor_6`,
    `min_extra_hum_sensor_7`,
    `min_extra_hum_sensor_8`,
    `min_average_windspeed`,
    `min_current_windspeed`,
    `min_avg_wind_10min`,
    `min_barometer`,
    `min_rain_rate_mm_min`,
    `min_solar_percent_of_max`,
    `min_uv_index`,
    `min_vp_solar_wm2`,
    `min_cloud_height`,
    `min_leaf_wetness_vp`,
    `min_soil_moisture_vp`,
    `min_day_rain`
  ) SELECT
    yesterday,
    COALESCE(MIN(out_temp), 0),
    COALESCE(MIN(in_temp), 0),
    COALESCE(MIN(soil_temp), 0),
    COALESCE(MIN(wmr968_extra_temp), 0),
    COALESCE(MIN(extra_temp_sensor_1), 0),
    COALESCE(MIN(extra_temp_sensor_2), 0),
    COALESCE(MIN(extra_temp_sensor_3), 0),
    COALESCE(MIN(extra_temp_sensor_4), 0),
    COALESCE(MIN(extra_temp_sensor_5), 0),
    COALESCE(MIN(extra_temp_sensor_6), 0),
    COALESCE(MIN(wind_chill), 0),
    COALESCE(MIN(humidex), 0),
    COALESCE(MIN(dew_point), 0),
    COALESCE(MIN(heat_index), 0),
    COALESCE(MIN(extra_temp_sensor_7), 0),
    COALESCE(MIN(extra_temp_sensor_8), 0),
    COALESCE(MIN(apparent_temp), 0),
    COALESCE(MIN(wet_bulb_temp), 0),
    COALESCE(MIN(out_hum), 0),
    COALESCE(MIN(in_hum), 0),
    COALESCE(MIN(wmr968_extra_hum), 0),
    COALESCE(MIN(extra_hum_sensor_1), 0),
    COALESCE(MIN(extra_hum_sensor_2), 0),
    COALESCE(MIN(extra_hum_sensor_3), 0),
    COALESCE(MIN(extra_hum_sensor_4), 0),
    COALESCE(MIN(extra_hum_sensor_5), 0),
    COALESCE(MIN(extra_hum_sensor_6), 0),
    COALESCE(MIN(extra_hum_sensor_7), 0),
    COALESCE(MIN(extra_hum_sensor_8), 0),
    COALESCE(MIN(average_windspeed), 0),
    COALESCE(MIN(current_windspeed), 0),
    COALESCE(MIN(avg_wind_10min), 0),
    COALESCE(MIN(barometer), 0),
    COALESCE(MIN(rain_rate_mm_min), 0),
    COALESCE(MIN(solar_percent_of_max), 0),
    COALESCE(MIN(uv_index), 0),
    COALESCE(MIN(vp_solar_wm2), 0),
    COALESCE(MIN(cloud_height), 0),
    COALESCE(MIN(leaf_wetness_vp), 0),
    COALESCE(MIN(soil_moisture_vp), 0),
    COALESCE(MIN(day_rain), 0)
  FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) = yesterday
  ON DUPLICATE KEY UPDATE
    min_out_temp = VALUES(min_out_temp),
    min_in_temp = VALUES(min_in_temp),
    min_soil_temp = VALUES(min_soil_temp),
    min_wmr968_extra_temp = VALUES(min_wmr968_extra_temp),
    min_extra_temp_sensor_1 = VALUES(min_extra_temp_sensor_1),
    min_extra_temp_sensor_2 = VALUES(min_extra_temp_sensor_2),
    min_extra_temp_sensor_3 = VALUES(min_extra_temp_sensor_3),
    min_extra_temp_sensor_4 = VALUES(min_extra_temp_sensor_4),
    min_extra_temp_sensor_5 = VALUES(min_extra_temp_sensor_5),
    min_extra_temp_sensor_6 = VALUES(min_extra_temp_sensor_6),
    min_wind_chill = VALUES(min_wind_chill),
    min_humidex = VALUES(min_humidex),
    min_dew_point = VALUES(min_dew_point),
    min_heat_index = VALUES(min_heat_index),
    min_extra_temp_sensor_7 = VALUES(min_extra_temp_sensor_7),
    min_extra_temp_sensor_8 = VALUES(min_extra_temp_sensor_8),
    min_apparent_temp = VALUES(min_apparent_temp),
    min_wet_bulb_temp = VALUES(min_wet_bulb_temp),
    min_out_hum = VALUES(min_out_hum),
    min_in_hum = VALUES(min_in_hum),
    min_wmr968_extra_hum = VALUES(min_wmr968_extra_hum),
    min_extra_hum_sensor_1 = VALUES(min_extra_hum_sensor_1),
    min_extra_hum_sensor_2 = VALUES(min_extra_hum_sensor_2),
    min_extra_hum_sensor_3 = VALUES(min_extra_hum_sensor_3),
    min_extra_hum_sensor_4 = VALUES(min_extra_hum_sensor_4),
    min_extra_hum_sensor_5 = VALUES(min_extra_hum_sensor_5),
    min_extra_hum_sensor_6 = VALUES(min_extra_hum_sensor_6),
    min_extra_hum_sensor_7 = VALUES(min_extra_hum_sensor_7),
    min_extra_hum_sensor_8 = VALUES(min_extra_hum_sensor_8),
    min_average_windspeed = VALUES(min_average_windspeed),
    min_current_windspeed = VALUES(min_current_windspeed),
    min_avg_wind_10min = VALUES(min_avg_wind_10min),
    min_barometer = VALUES(min_barometer),
    min_rain_rate_mm_min = VALUES(min_rain_rate_mm_min),
    min_solar_percent_of_max = VALUES(min_solar_percent_of_max),
    min_uv_index = VALUES(min_uv_index),
    min_vp_solar_wm2 = VALUES(min_vp_solar_wm2),
    min_cloud_height = VALUES(min_cloud_height),
    min_leaf_wetness_vp = VALUES(min_leaf_wetness_vp),
    min_soil_moisture_vp = VALUES(min_soil_moisture_vp),
    min_day_rain = VALUES(min_day_rain);

  -- Insert avg values
  INSERT INTO weather_daily_avg (
    `date`,
    `avg_out_temp`,
    `avg_in_temp`,
    `avg_soil_temp`,
    `avg_wmr968_extra_temp`,
    `avg_extra_temp_sensor_1`,
    `avg_extra_temp_sensor_2`,
    `avg_extra_temp_sensor_3`,
    `avg_extra_temp_sensor_4`,
    `avg_extra_temp_sensor_5`,
    `avg_extra_temp_sensor_6`,
    `avg_wind_chill`,
    `avg_humidex`,
    `avg_dew_point`,
    `avg_heat_index`,
    `avg_extra_temp_sensor_7`,
    `avg_extra_temp_sensor_8`,
    `avg_apparent_temp`,
    `avg_wet_bulb_temp`,
    `avg_out_hum`,
    `avg_in_hum`,
    `avg_wmr968_extra_hum`,
    `avg_extra_hum_sensor_1`,
    `avg_extra_hum_sensor_2`,
    `avg_extra_hum_sensor_3`,
    `avg_extra_hum_sensor_4`,
    `avg_extra_hum_sensor_5`,
    `avg_extra_hum_sensor_6`,
    `avg_extra_hum_sensor_7`,
    `avg_extra_hum_sensor_8`,
    `avg_average_windspeed`,
    `avg_current_windspeed`,
    `avg_avg_wind_10min`,
    `avg_barometer`,
    `avg_rain_rate_mm_min`,
    `avg_solar_percent_of_max`,
    `avg_uv_index`,
    `avg_vp_solar_wm2`,
    `avg_cloud_height`,
    `avg_leaf_wetness_vp`,
    `avg_soil_moisture_vp`,
    `avg_day_rain`
  ) SELECT
    yesterday,
    COALESCE(AVG(out_temp), 0),
    COALESCE(AVG(in_temp), 0),
    COALESCE(AVG(soil_temp), 0),
    COALESCE(AVG(wmr968_extra_temp), 0),
    COALESCE(AVG(extra_temp_sensor_1), 0),
    COALESCE(AVG(extra_temp_sensor_2), 0),
    COALESCE(AVG(extra_temp_sensor_3), 0),
    COALESCE(AVG(extra_temp_sensor_4), 0),
    COALESCE(AVG(extra_temp_sensor_5), 0),
    COALESCE(AVG(extra_temp_sensor_6), 0),
    COALESCE(AVG(wind_chill), 0),
    COALESCE(AVG(humidex), 0),
    COALESCE(AVG(dew_point), 0),
    COALESCE(AVG(heat_index), 0),
    COALESCE(AVG(extra_temp_sensor_7), 0),
    COALESCE(AVG(extra_temp_sensor_8), 0),
    COALESCE(AVG(apparent_temp), 0),
    COALESCE(AVG(wet_bulb_temp), 0),
    COALESCE(AVG(out_hum), 0),
    COALESCE(AVG(in_hum), 0),
    COALESCE(AVG(wmr968_extra_hum), 0),
    COALESCE(AVG(extra_hum_sensor_1), 0),
    COALESCE(AVG(extra_hum_sensor_2), 0),
    COALESCE(AVG(extra_hum_sensor_3), 0),
    COALESCE(AVG(extra_hum_sensor_4), 0),
    COALESCE(AVG(extra_hum_sensor_5), 0),
    COALESCE(AVG(extra_hum_sensor_6), 0),
    COALESCE(AVG(extra_hum_sensor_7), 0),
    COALESCE(AVG(extra_hum_sensor_8), 0),
    COALESCE(AVG(average_windspeed), 0),
    COALESCE(AVG(current_windspeed), 0),
    COALESCE(AVG(avg_wind_10min), 0),
    COALESCE(AVG(barometer), 0),
    COALESCE(AVG(rain_rate_mm_min), 0),
    COALESCE(AVG(solar_percent_of_max), 0),
    COALESCE(AVG(uv_index), 0),
    COALESCE(AVG(vp_solar_wm2), 0),
    COALESCE(AVG(cloud_height), 0),
    COALESCE(AVG(leaf_wetness_vp), 0),
    COALESCE(AVG(soil_moisture_vp), 0),
    COALESCE(AVG(day_rain), 0)
  FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) = yesterday
  ON DUPLICATE KEY UPDATE
    avg_out_temp = VALUES(avg_out_temp),
    avg_in_temp = VALUES(avg_in_temp),
    avg_soil_temp = VALUES(avg_soil_temp),
    avg_wmr968_extra_temp = VALUES(avg_wmr968_extra_temp),
    avg_extra_temp_sensor_1 = VALUES(avg_extra_temp_sensor_1),
    avg_extra_temp_sensor_2 = VALUES(avg_extra_temp_sensor_2),
    avg_extra_temp_sensor_3 = VALUES(avg_extra_temp_sensor_3),
    avg_extra_temp_sensor_4 = VALUES(avg_extra_temp_sensor_4),
    avg_extra_temp_sensor_5 = VALUES(avg_extra_temp_sensor_5),
    avg_extra_temp_sensor_6 = VALUES(avg_extra_temp_sensor_6),
    avg_wind_chill = VALUES(avg_wind_chill),
    avg_humidex = VALUES(avg_humidex),
    avg_dew_point = VALUES(avg_dew_point),
    avg_heat_index = VALUES(avg_heat_index),
    avg_extra_temp_sensor_7 = VALUES(avg_extra_temp_sensor_7),
    avg_extra_temp_sensor_8 = VALUES(avg_extra_temp_sensor_8),
    avg_apparent_temp = VALUES(avg_apparent_temp),
    avg_wet_bulb_temp = VALUES(avg_wet_bulb_temp),
   avg_out_hum = VALUES(avg_out_hum),
    avg_in_hum = VALUES(avg_in_hum),
    avg_wmr968_extra_hum = VALUES(avg_wmr968_extra_hum),
    avg_extra_hum_sensor_1 = VALUES(avg_extra_hum_sensor_1),
    avg_extra_hum_sensor_2 = VALUES(avg_extra_hum_sensor_2),
    avg_extra_hum_sensor_3 = VALUES(avg_extra_hum_sensor_3),
    avg_extra_hum_sensor_4 = VALUES(avg_extra_hum_sensor_4),
    avg_extra_hum_sensor_5 = VALUES(avg_extra_hum_sensor_5),
    avg_extra_hum_sensor_6 = VALUES(avg_extra_hum_sensor_6),
    avg_extra_hum_sensor_7 = VALUES(avg_extra_hum_sensor_7),
    avg_extra_hum_sensor_8 = VALUES(avg_extra_hum_sensor_8),
    avg_average_windspeed = VALUES(avg_average_windspeed),
    avg_current_windspeed = VALUES(avg_current_windspeed),
    avg_avg_wind_10min = VALUES(avg_avg_wind_10min),
    avg_barometer = VALUES(avg_barometer),
    avg_rain_rate_mm_min = VALUES(avg_rain_rate_mm_min),
    avg_solar_percent_of_max = VALUES(avg_solar_percent_of_max),
    avg_uv_index = VALUES(avg_uv_index),
    avg_vp_solar_wm2 = VALUES(avg_vp_solar_wm2),
    avg_cloud_height = VALUES(avg_cloud_height),
    avg_leaf_wetness_vp = VALUES(avg_leaf_wetness_vp),
    avg_soil_moisture_vp = VALUES(avg_soil_moisture_vp),
    avg_day_rain = VALUES(avg_day_rain);

  -- Wipe old readings
  DELETE FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) < CURDATE();
END