-- Drop existing event if exists
DROP EVENT IF EXISTS daily_weather_wipe;

-- Create the updated event
CREATE EVENT daily_weather_wipe
ON SCHEDULE EVERY 1 DAY
STARTS '2025-07-22 00:00:00'  -- Adjust start date if needed
DO
BEGIN
  DECLARE yesterday DATE;
  SET yesterday = CURDATE() - INTERVAL 1 DAY;

  -- Insert max values for yesterday
  INSERT INTO weather_daily_max (
    `date`,
    `max_station_id`,
    `max_average_windspeed`,
    `max_current_windspeed`,
    `max_wind_dir`,
    `max_out_temp`,
    `max_out_hum`,
    `max_barometer`,
    `max_day_rain`,
    `max_month_rain`,
    `max_year_rain`,
    `max_rain_rate_mm_min`,
    `max_rain_rate_max_mm_min`,
    `max_in_temp`,
    `max_in_hum`,
    `max_soil_temp`,
    `max_forecast_icon_code`,
    `max_wmr968_extra_temp`,
    `max_wmr968_extra_hum`,
    `max_wmr968_extra_sensor`,
    `max_yesterday_rain`,
    `max_extra_temp_sensor_1`,
    `max_extra_temp_sensor_2`,
    `max_extra_temp_sensor_3`,
    `max_extra_temp_sensor_4`,
    `max_extra_temp_sensor_5`,
    `max_extra_temp_sensor_6`,
    `max_extra_hum_sensor_1`,
    `max_extra_hum_sensor_2`,
    `max_extra_hum_sensor_3`,
    `max_measurement_hour`,
    `max_measurement_minute`,
    `max_measurement_second`,
    `max_location_label`,
    `max_lightning_count_since_noon`,
    `max_solar_percent_of_max`,
    `max_measurement_day`,
    `max_measurement_month`,
    `max_wmr968_batt1`,
    `max_wmr968_batt2`,
    `max_wmr968_batt3`,
    `max_wmr968_batt4`,
    `max_wmr968_batt5`,
    `max_wmr968_batt6`,
    `max_wmr968_batt7`,
    `max_wind_chill`,
    `max_humidex`,
    `max_max_temp_today`,
    `max_min_temp_today`,
    `max_current_condition_icon`,
    `max_sky_condition_text`,
    `max_baro_trend_last_hour`,
    `max_windspeed_hour_01`,
    `max_windspeed_hour_02`,
    `max_windspeed_hour_03`,
    `max_windspeed_hour_04`,
    `max_windspeed_hour_05`,
    `max_windspeed_hour_06`,
    `max_windspeed_hour_07`,
    `max_windspeed_hour_08`,
    `max_windspeed_hour_09`,
    `max_windspeed_hour_10`,
    `max_windspeed_hour_11`,
    `max_windspeed_hour_12`,
    `max_windspeed_hour_13`,
    `max_windspeed_hour_14`,
    `max_windspeed_hour_15`,
    `max_windspeed_hour_16`,
    `max_windspeed_hour_17`,
    `max_windspeed_hour_18`,
    `max_windspeed_hour_19`,
    `max_windspeed_hour_20`,
    `max_max_wind_gust`,
    `max_dew_point`,
    `max_cloud_height`,
    `max_current_date`,
    `max_max_humidex`,
    `max_min_humidex`,
    `max_max_windchill`,
    `max_min_windchill`,
    `max_uv_index`,
    `max_hr_windspeed_01`,
    `max_hr_windspeed_02`,
    `max_hr_windspeed_03`,
    `max_hr_windspeed_04`,
    `max_hr_windspeed_05`,
    `max_hr_windspeed_06`,
    `max_hr_windspeed_07`,
    `max_hr_windspeed_08`,
    `max_hr_windspeed_09`,
    `max_hr_windspeed_10`,
    `max_hr_temp_01`,
    `max_hr_temp_02`,
    `max_hr_temp_03`,
    `max_hr_temp_04`,
    `max_hr_temp_05`,
    `max_hr_temp_06`,
    `max_hr_temp_07`,
    `max_hr_temp_08`,
    `max_hr_temp_09`,
    `max_hr_temp_10`,
    `max_hr_rain_01`,
    `max_hr_rain_02`,
    `max_hr_rain_03`,
    `max_hr_rain_04`,
    `max_hr_rain_05`,
    `max_hr_rain_06`,
    `max_hr_rain_07`,
    `max_hr_rain_08`,
    `max_hr_rain_09`,
    `max_hr_rain_10`,
    `max_max_heat_index`,
    `max_min_heat_index`,
    `max_heat_index`,
    `max_max_avg_windspeed_today`,
    `max_lightning_count_last_minute`,
    `max_last_lightning_time`,
    `max_last_lightning_date`,
    `max_avg_wind_direction`,
    `max_nexstorm_last_strike_distance`,
    `max_nexstorm_last_strike_bearing`,
    `max_extra_temp_sensor_7`,
    `max_extra_temp_sensor_8`,
    `max_extra_hum_sensor_4`,
    `max_extra_hum_sensor_5`,
    `max_extra_hum_sensor_6`,
    `max_extra_hum_sensor_7`,
    `max_extra_hum_sensor_8`,
    `max_vp_solar_wm2`,
    `max_max_in_temp`,
    `max_min_in_temp`,
    `max_apparent_temp`,
    `max_max_baro`,
    `max_min_baro`,
    `max_max_gust_last_hour`,
    `max_max_gust_last_hour_time`,
    `max_max_gust_today_time`,
    `max_max_apparent_temp`,
    `max_min_apparent_temp`,
    `max_max_dew_point`,
    `max_min_dew_point`,
    `max_max_gust_last_minute`,
    `max_current_year`,
    `max_thsw_index`,
    `max_temp_trend`,
    `max_humidity_trend`,
    `max_humidex_trend`,
    `max_hr_wind_dir_01`,
    `max_hr_wind_dir_02`,
    `max_hr_wind_dir_03`,
    `max_hr_wind_dir_04`,
    `max_hr_wind_dir_05`,
    `max_hr_wind_dir_06`,
    `max_hr_wind_dir_07`,
    `max_hr_wind_dir_08`,
    `max_hr_wind_dir_09`,
    `max_hr_wind_dir_10`,
    `max_leaf_wetness_vp`,
    `max_soil_moisture_vp`,
    `max_avg_wind_10min`,
    `max_wet_bulb_temp`,
    `max_latitude`,
    `max_longitude`,
    `max_rain_9am_reset`,
    `max_daily_high_humidity`,
    `max_daily_low_humidity`,
    `max_rain_midnight_reset`,
    `max_daily_low_windchill_time`,
    `max_cost_channel_1_watts`,
    `max_cost_channel_2_watts`,
    `max_cost_channel_3_watts`,
    `max_cost_channel_4_watts`,
    `max_cost_channel_5_watts`,
    `max_cost_channel_6_watts`,
    `max_daily_wind_run_km`,
    `max_daily_max_temp_time`,
    `max_daily_min_temp_time`,
    `max_avg_wind_dir_10min`,
    `max_firmware_version`
  ) SELECT
    yesterday,
    MAX(`station_id`),
    MAX(`average_windspeed`),
    MAX(`current_windspeed`),
    MAX(`wind_dir`),
    MAX(`out_temp`),
    MAX(`out_hum`),
    MAX(`barometer`),
    MAX(`day_rain`),
    MAX(`month_rain`),
    MAX(`year_rain`),
    MAX(`rain_rate_mm_min`),
    MAX(`rain_rate_max_mm_min`),
    MAX(`in_temp`),
    MAX(`in_hum`),
    MAX(`soil_temp`),
    MAX(`forecast_icon_code`),
    MAX(`wmr968_extra_temp`),
    MAX(`wmr968_extra_hum`),
    MAX(`wmr968_extra_sensor`),
    MAX(`yesterday_rain`),
    MAX(`extra_temp_sensor_1`),
    MAX(`extra_temp_sensor_2`),
    MAX(`extra_temp_sensor_3`),
    MAX(`extra_temp_sensor_4`),
    MAX(`extra_temp_sensor_5`),
    MAX(`extra_temp_sensor_6`),
    MAX(`extra_hum_sensor_1`),
    MAX(`extra_hum_sensor_2`),
    MAX(`extra_hum_sensor_3`),
    MAX(`measurement_hour`),
    MAX(`measurement_minute`),
    MAX(`measurement_second`),
    MAX(`location_label`),
    MAX(`lightning_count_since_noon`),
    MAX(`solar_percent_of_max`),
    MAX(`measurement_day`),
    MAX(`measurement_month`),
    MAX(`wmr968_batt1`),
    MAX(`wmr968_batt2`),
    MAX(`wmr968_batt3`),
    MAX(`wmr968_batt4`),
    MAX(`wmr968_batt5`),
    MAX(`wmr968_batt6`),
    MAX(`wmr968_batt7`),
    MAX(`wind_chill`),
    MAX(`humidex`),
    MAX(`max_temp_today`),
    MAX(`min_temp_today`),
    MAX(`current_condition_icon`),
    MAX(`sky_condition_text`),
    MAX(`baro_trend_last_hour`),
    MAX(`windspeed_hour_01`),
    MAX(`windspeed_hour_02`),
    MAX(`windspeed_hour_03`),
    MAX(`windspeed_hour_04`),
    MAX(`windspeed_hour_05`),
    MAX(`windspeed_hour_06`),
    MAX(`windspeed_hour_07`),
    MAX(`windspeed_hour_08`),
    MAX(`windspeed_hour_09`),
    MAX(`windspeed_hour_10`),
    MAX(`windspeed_hour_11`),
    MAX(`windspeed_hour_12`),
    MAX(`windspeed_hour_13`),
    MAX(`windspeed_hour_14`),
    MAX(`windspeed_hour_15`),
    MAX(`windspeed_hour_16`),
    MAX(`windspeed_hour_17`),
    MAX(`windspeed_hour_18`),
    MAX(`windspeed_hour_19`),
    MAX(`windspeed_hour_20`),
    MAX(`max_wind_gust`),
    MAX(`dew_point`),
    MAX(`cloud_height`),
    MAX(`current_date`),
    MAX(`max_humidex`),
    MAX(`min_humidex`),
    MAX(`max_windchill`),
    MAX(`min_windchill`),
    MAX(`uv_index`),
    MAX(`hr_windspeed_01`),
    MAX(`hr_windspeed_02`),
    MAX(`hr_windspeed_03`),
    MAX(`hr_windspeed_04`),
    MAX(`hr_windspeed_05`),
    MAX(`hr_windspeed_06`),
    MAX(`hr_windspeed_07`),
    MAX(`hr_windspeed_08`),
    MAX(`hr_windspeed_09`),
    MAX(`hr_windspeed_10`),
    MAX(`hr_temp_01`),
    MAX(`hr_temp_02`),
    MAX(`hr_temp_03`),
    MAX(`hr_temp_04`),
    MAX(`hr_temp_05`),
    MAX(`hr_temp_06`),
    MAX(`hr_temp_07`),
    MAX(`hr_temp_08`),
    MAX(`hr_temp_09`),
    MAX(`hr_temp_10`),
    MAX(`hr_rain_01`),
    MAX(`hr_rain_02`),
    MAX(`hr_rain_03`),
    MAX(`hr_rain_04`),
    MAX(`hr_rain_05`),
    MAX(`hr_rain_06`),
    MAX(`hr_rain_07`),
    MAX(`hr_rain_08`),
    MAX(`hr_rain_09`),
    MAX(`hr_rain_10`),
    MAX(`max_heat_index`),
    MAX(`min_heat_index`),
    MAX(`heat_index`),
    MAX(`max_avg_windspeed_today`),
    MAX(`lightning_count_last_minute`),
    MAX(`last_lightning_time`),
    MAX(`last_lightning_date`),
    MAX(`avg_wind_direction`),
    MAX(`nexstorm_last_strike_distance`),
    MAX(`nexstorm_last_strike_bearing`),
    MAX(`extra_temp_sensor_7`),
    MAX(`extra_temp_sensor_8`),
    MAX(`extra_hum_sensor_4`),
    MAX(`extra_hum_sensor_5`),
    MAX(`extra_hum_sensor_6`),
    MAX(`extra_hum_sensor_7`),
    MAX(`extra_hum_sensor_8`),
    MAX(`vp_solar_wm2`),
    MAX(`max_in_temp`),
    MAX(`min_in_temp`),
    MAX(`apparent_temp`),
    MAX(`max_baro`),
    MAX(`min_baro`),
    MAX(`max_gust_last_hour`),
    MAX(`max_gust_last_hour_time`),
    MAX(`max_gust_today_time`),
    MAX(`max_apparent_temp`),
    MAX(`min_apparent_temp`),
    MAX(`max_dew_point`),
    MAX(`min_dew_point`),
    MAX(`max_gust_last_minute`),
    MAX(`current_year`),
    MAX(`thsw_index`),
    MAX(`temp_trend`),
    MAX(`humidity_trend`),
    MAX(`humidex_trend`),
    MAX(`hr_wind_dir_01`),
    MAX(`hr_wind_dir_02`),
    MAX(`hr_wind_dir_03`),
    MAX(`hr_wind_dir_04`),
    MAX(`hr_wind_dir_05`),
    MAX(`hr_wind_dir_06`),
    MAX(`hr_wind_dir_07`),
    MAX(`hr_wind_dir_08`),
    MAX(`hr_wind_dir_09`),
    MAX(`hr_wind_dir_10`),
    MAX(`leaf_wetness_vp`),
    MAX(`soil_moisture_vp`),
    MAX(`avg_wind_10min`),
    MAX(`wet_bulb_temp`),
    MAX(`latitude`),
    MAX(`longitude`),
    MAX(`rain_9am_reset`),
    MAX(`daily_high_humidity`),
    MAX(`daily_low_humidity`),
    MAX(`rain_midnight_reset`),
    MAX(`daily_low_windchill_time`),
    MAX(`cost_channel_1_watts`),
    MAX(`cost_channel_2_watts`),
    MAX(`cost_channel_3_watts`),
    MAX(`cost_channel_4_watts`),
    MAX(`cost_channel_5_watts`),
    MAX(`cost_channel_6_watts`),
    MAX(`daily_wind_run_km`),
    MAX(`daily_max_temp_time`),
    MAX(`daily_min_temp_time`),
    MAX(`avg_wind_dir_10min`),
    MAX(`firmware_version`)
  FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) = yesterday
  ON DUPLICATE KEY UPDATE
    max_station_id = VALUES(max_station_id),
    max_average_windspeed = VALUES(max_average_windspeed),
    max_current_windspeed = VALUES(max_current_windspeed),
    max_wind_dir = VALUES(max_wind_dir),
    max_out_temp = VALUES(max_out_temp),
    max_out_hum = VALUES(max_out_hum),
    max_barometer = VALUES(max_barometer),
    max_day_rain = VALUES(max_day_rain),
    max_month_rain = VALUES(max_month_rain),
    max_year_rain = VALUES(max_year_rain),
    max_rain_rate_mm_min = VALUES(max_rain_rate_mm_min),
    max_rain_rate_max_mm_min = VALUES(max_rain_rate_max_mm_min),
    max_in_temp = VALUES(max_in_temp),
    max_in_hum = VALUES(max_in_hum),
    max_soil_temp = VALUES(max_soil_temp),
    max_forecast_icon_code = VALUES(max_forecast_icon_code),
    max_wmr968_extra_temp = VALUES(max_wmr968_extra_temp),
    max_wmr968_extra_hum = VALUES(max_wmr968_extra_hum),
    max_wmr968_extra_sensor = VALUES(max_wmr968_extra_sensor),
    max_yesterday_rain = VALUES(max_yesterday_rain),
    max_extra_temp_sensor_1 = VALUES(max_extra_temp_sensor_1),
    max_extra_temp_sensor_2 = VALUES(max_extra_temp_sensor_2),
    max_extra_temp_sensor_3 = VALUES(max_extra_temp_sensor_3),
    max_extra_temp_sensor_4 = VALUES(max_extra_temp_sensor_4),
    max_extra_temp_sensor_5 = VALUES(max_extra_temp_sensor_5),
    max_extra_temp_sensor_6 = VALUES(max_extra_temp_sensor_6),
    max_extra_hum_sensor_1 = VALUES(max_extra_hum_sensor_1),
    max_extra_hum_sensor_2 = VALUES(max_extra_hum_sensor_2),
    max_extra_hum_sensor_3 = VALUES(max_extra_hum_sensor_3),
    max_measurement_hour = VALUES(max_measurement_hour),
    max_measurement_minute = VALUES(max_measurement_minute),
    max_measurement_second = VALUES(max_measurement_second),
    max_location_label = VALUES(max_location_label),
    max_lightning_count_since_noon = VALUES(max_lightning_count_since_noon),
    max_solar_percent_of_max = VALUES(max_solar_percent_of_max),
    max_measurement_day = VALUES(max_measurement_day),
    max_measurement_month = VALUES(max_measurement_month),
    max_wmr968_batt1 = VALUES(max_wmr968_batt1),
    max_wmr968_batt2 = VALUES(max_wmr968_batt2),
    max_wmr968_batt3 = VALUES(max_wmr968_batt3),
    max_wmr968_batt4 = VALUES(max_wmr968_batt4),
    max_wmr968_batt5 = VALUES(max_wmr968_batt5),
    max_wmr968_batt6 = VALUES(max_wmr968_batt6),
    max_wmr968_batt7 = VALUES(max_wmr968_batt7),
    max_wind_chill = VALUES(max_wind_chill),
    max_humidex = VALUES(max_humidex),
    max_max_temp_today = VALUES(max_max_temp_today),
    max_min_temp_today = VALUES(max_min_temp_today),
    max_current_condition_icon = VALUES(max_current_condition_icon),
    max_sky_condition_text = VALUES(max_sky_condition_text),
    max_baro_trend_last_hour = VALUES(max_baro_trend_last_hour),
    max_windspeed_hour_01 = VALUES(max_windspeed_hour_01),
    max_windspeed_hour_02 = VALUES(max_windspeed_hour_02),
    max_windspeed_hour_03 = VALUES(max_windspeed_hour_03),
    max_windspeed_hour_04 = VALUES(max_windspeed_hour_04),
    max_windspeed_hour_05 = VALUES(max_windspeed_hour_05),
    max_windspeed_hour_06 = VALUES(max_windspeed_hour_06),
    max_windspeed_hour_07 = VALUES(max_windspeed_hour_07),
    max_windspeed_hour_08 = VALUES(max_windspeed_hour_08),
    max_windspeed_hour_09 = VALUES(max_windspeed_hour_09),
    max_windspeed_hour_10 = VALUES(max_windspeed_hour_10),
    max_windspeed_hour_11 = VALUES(max_windspeed_hour_11),
    max_windspeed_hour_12 = VALUES(max_windspeed_hour_12),
    max_windspeed_hour_13 = VALUES(max_windspeed_hour_13),
    max_windspeed_hour_14 = VALUES(max_windspeed_hour_14),
    max_windspeed_hour_15 = VALUES(max_windspeed_hour_15),
    max_windspeed_hour_16 = VALUES(max_windspeed_hour_16),
    max_windspeed_hour_17 = VALUES(max_windspeed_hour_17),
    max_windspeed_hour_18 = VALUES(max_windspeed_hour_18),
    max_windspeed_hour_19 = VALUES(max_windspeed_hour_19),
    max_windspeed_hour_20 = VALUES(max_windspeed_hour_20),
    max_max_wind_gust = VALUES(max_max_wind_gust),
    max_dew_point = VALUES(max_dew_point),
    max_cloud_height = VALUES(max_cloud_height),
    max_current_date = VALUES(max_current_date),
    max_max_humidex = VALUES(max_max_humidex),
    max_min_humidex = VALUES(max_min_humidex),
    max_max_windchill = VALUES(max_max_windchill),
    max_min_windchill = VALUES(max_min_windchill),
    max_uv_index = VALUES(max_uv_index),
    max_hr_windspeed_01 = VALUES(max_hr_windspeed_01),
    max_hr_windspeed_02 = VALUES(max_hr_windspeed_02),
    max_hr_windspeed_03 = VALUES(max_hr_windspeed_03),
    max_hr_windspeed_04 = VALUES(max_hr_windspeed_04),
    max_hr_windspeed_05 = VALUES(max_hr_windspeed_05),
    max_hr_windspeed_06 = VALUES(max_hr_windspeed_06),
    max_hr_windspeed_07 = VALUES(max_hr_windspeed_07),
    max_hr_windspeed_08 = VALUES(max_hr_windspeed_08),
    max_hr_windspeed_09 = VALUES(max_hr_windspeed_09),
    max_hr_windspeed_10 = VALUES(max_hr_windspeed_10),
    max_hr_temp_01 = VALUES(max_hr_temp_01),
    max_hr_temp_02 = VALUES(max_hr_temp_02),
    max_hr_temp_03 = VALUES(max_hr_temp_03),
    max_hr_temp_04 = VALUES(max_hr_temp_04),
    max_hr_temp_05 = VALUES(max_hr_temp_05),
    max_hr_temp_06 = VALUES(max_hr_temp_06),
    max_hr_temp_07 = VALUES(max_hr_temp_07),
    max_hr_temp_08 = VALUES(max_hr_temp_08),
    max_hr_temp_09 = VALUES(max_hr_temp_09),
    max_hr_temp_10 = VALUES(max_hr_temp_10),
    max_hr_rain_01 = VALUES(max_hr_rain_01),
    max_hr_rain_02 = VALUES(max_hr_rain_02),
    max_hr_rain_03 = VALUES(max_hr_rain_03),
    max_hr_rain_04 = VALUES(max_hr_rain_04),
    max_hr_rain_05 = VALUES(max_hr_rain_05),
    max_hr_rain_06 = VALUES(max_hr_rain_06),
    max_hr_rain_07 = VALUES(max_hr_rain_07),
    max_hr_rain_08 = VALUES(max_hr_rain_08),
    max_hr_rain_09 = VALUES(max_hr_rain_09),
    max_hr_rain_10 = VALUES(max_hr_rain_10),
    max_max_heat_index = VALUES(max_max_heat_index),
    max_min_heat_index = VALUES(max_min_heat_index),
    max_heat_index = VALUES(max_heat_index),
    max_max_avg_windspeed_today = VALUES(max_max_avg_windspeed_today),
    max_lightning_count_last_minute = VALUES(max_lightning_count_last_minute),
    max_last_lightning_time = VALUES(max_last_lightning_time),
    max_last_lightning_date = VALUES(max_last_lightning_date),
    max_avg_wind_direction = VALUES(max_avg_wind_direction),
    max_nexstorm_last_strike_distance = VALUES(max_nexstorm_last_strike_distance),
    max_nexstorm_last_strike_bearing = VALUES(max_nexstorm_last_strike_bearing),
    max_extra_temp_sensor_7 = VALUES(max_extra_temp_sensor_7),
    max_extra_temp_sensor_8 = VALUES(max_extra_temp_sensor_8),
    max_extra_hum_sensor_4 = VALUES(max_extra_hum_sensor_4),
    max_extra_hum_sensor_5 = VALUES(max_extra_hum_sensor_5),
    max_extra_hum_sensor_6 = VALUES(max_extra_hum_sensor_6),
    max_extra_hum_sensor_7 = VALUES(max_extra_hum_sensor_7),
    max_extra_hum_sensor_8 = VALUES(max_extra_hum_sensor_8),
    max_vp_solar_wm2 = VALUES(max_vp_solar_wm2),
    max_max_in_temp = VALUES(max_max_in_temp),
    max_min_in_temp = VALUES(max_min_in_temp),
    max_apparent_temp = VALUES(max_apparent_temp),
    max_max_baro = VALUES(max_max_baro),
    max_min_baro = VALUES(max_min_baro),
    max_max_gust_last_hour = VALUES(max_max_gust_last_hour),
    max_max_gust_last_hour_time = VALUES(max_max_gust_last_hour_time),
    max_max_gust_today_time = VALUES(max_max_gust_today_time),
    max_max_apparent_temp = VALUES(max_max_apparent_temp),
    max_min_apparent_temp = VALUES(max_min_apparent_temp),
    max_max_dew_point = VALUES(max_max_dew_point),
    max_min_dew_point = VALUES(max_min_dew_point),
    max_max_gust_last_minute = VALUES(max_max_gust_last_minute),
    max_current_year = VALUES(max_current_year),
    max_thsw_index = VALUES(max_thsw_index),
    max_temp_trend = VALUES(max_temp_trend),
    max_humidity_trend = VALUES(max_humidity_trend),
    max_humidex_trend = VALUES(max_humidex_trend),
    max_hr_wind_dir_01 = VALUES(max_hr_wind_dir_01),
    max_hr_wind_dir_02 = VALUES(max_hr_wind_dir_02),
    max_hr_wind_dir_03 = VALUES(max_hr_wind_dir_03),
    max_hr_wind_dir_04 = VALUES(max_hr_wind_dir_04),
    max_hr_wind_dir_05 = VALUES(max_hr_wind_dir_05),
    max_hr_wind_dir_06 = VALUES(max_hr_wind_dir_06),
    max_hr_wind_dir_07 = VALUES(max_hr_wind_dir_07),
    max_hr_wind_dir_08 = VALUES(max_hr_wind_dir_08),
    max_hr_wind_dir_09 = VALUES(max_hr_wind_dir_09),
    max_hr_wind_dir_10 = VALUES(max_hr_wind_dir_10),
    max_leaf_wetness_vp = VALUES(max_leaf_wetness_vp),
    max_soil_moisture_vp = VALUES(max_soil_moisture_vp),
    max_avg_wind_10min = VALUES(max_avg_wind_10min),
    max_wet_bulb_temp = VALUES(max_wet_bulb_temp),
    max_latitude = VALUES(max_latitude),
    max_longitude = VALUES(max_longitude),
    max_rain_9am_reset = VALUES(max_rain_9am_reset),
    max_daily_high_humidity = VALUES(max_daily_high_humidity),
    max_daily_low_humidity = VALUES(max_daily_low_humidity),
    max_rain_midnight_reset = VALUES(max_rain_midnight_reset),
    max_daily_low_windchill_time = VALUES(max_daily_low_windchill_time),
    max_cost_channel_1_watts = VALUES(max_cost_channel_1_watts),
    max_cost_channel_2_watts = VALUES(max_cost_channel_2_watts),
    max_cost_channel_3_watts = VALUES(max_cost_channel_3_watts),
    max_cost_channel_4_watts = VALUES(max_cost_channel_4_watts),
    max_cost_channel_5_watts = VALUES(max_cost_channel_5_watts),
    max_cost_channel_6_watts = VALUES(max_cost_channel_6_watts),
    max_daily_wind_run_km = VALUES(max_daily_wind_run_km),
    max_daily_max_temp_time = VALUES(max_daily_max_temp_time),
    max_daily_min_temp_time = VALUES(max_daily_min_temp_time),
    max_avg_wind_dir_10min = VALUES(max_avg_wind_dir_10min),
    max_firmware_version = VALUES(max_firmware_version);

  -- Insert min values for yesterday
  INSERT INTO weather_daily_min (
    `date`,
    `min_station_id`,
    `min_average_windspeed`,
    `min_current_windspeed`,
    `min_wind_dir`,
    `min_out_temp`,
    `min_out_hum`,
    `min_barometer`,
    `min_day_rain`,
    `min_month_rain`,
    `min_year_rain`,
    `min_rain_rate_mm_min`,
    `min_rain_rate_max_mm_min`,
    `min_in_temp`,
    `min_in_hum`,
    `min_soil_temp`,
    `min_forecast_icon_code`,
    `min_wmr968_extra_temp`,
    `min_wmr968_extra_hum`,
    `min_wmr968_extra_sensor`,
    `min_yesterday_rain`,
    `min_extra_temp_sensor_1`,
    `min_extra_temp_sensor_2`,
    `min_extra_temp_sensor_3`,
    `min_extra_temp_sensor_4`,
    `min_extra_temp_sensor_5`,
    `min_extra_temp_sensor_6`,
    `min_extra_hum_sensor_1`,
    `min_extra_hum_sensor_2`,
    `min_extra_hum_sensor_3`,
    `min_measurement_hour`,
    `min_measurement_minute`,
    `min_measurement_second`,
    `min_location_label`,
    `min_lightning_count_since_noon`,
    `min_solar_percent_of_max`,
    `min_measurement_day`,
    `min_measurement_month`,
    `min_wmr968_batt1`,
    `min_wmr968_batt2`,
    `min_wmr968_batt3`,
    `min_wmr968_batt4`,
    `min_wmr968_batt5`,
    `min_wmr968_batt6`,
    `min_wmr968_batt7`,
    `min_wind_chill`,
    `min_humidex`,
    `min_max_temp_today`,
    `min_min_temp_today`,
    `min_current_condition_icon`,
    `min_sky_condition_text`,
    `min_baro_trend_last_hour`,
    `min_windspeed_hour_01`,
    `min_windspeed_hour_02`,
    `min_windspeed_hour_03`,
    `min_windspeed_hour_04`,
    `min_windspeed_hour_05`,
    `min_windspeed_hour_06`,
    `min_windspeed_hour_07`,
    `min_windspeed_hour_08`,
    `min_windspeed_hour_09`,
    `min_windspeed_hour_10`,
    `min_windspeed_hour_11`,
    `min_windspeed_hour_12`,
    `min_windspeed_hour_13`,
    `min_windspeed_hour_14`,
    `min_windspeed_hour_15`,
    `min_windspeed_hour_16`,
    `min_windspeed_hour_17`,
    `min_windspeed_hour_18`,
    `min_windspeed_hour_19`,
    `min_windspeed_hour_20`,
    `min_max_wind_gust`,
    `min_dew_point`,
    `min_cloud_height`,
    `min_current_date`,
    `min_max_humidex`,
    `min_min_humidex`,
    `min_max_windchill`,
    `min_min_windchill`,
    `min_uv_index`,
    `min_hr_windspeed_01`,
    `min_hr_windspeed_02`,
    `min_hr_windspeed_03`,
    `min_hr_windspeed_04`,
    `min_hr_windspeed_05`,
    `min_hr_windspeed_06`,
    `min_hr_windspeed_07`,
    `min_hr_windspeed_08`,
    `min_hr_windspeed_09`,
    `min_hr_windspeed_10`,
    `min_hr_temp_01`,
    `min_hr_temp_02`,
    `min_hr_temp_03`,
    `min_hr_temp_04`,
    `min_hr_temp_05`,
    `min_hr_temp_06`,
    `min_hr_temp_07`,
    `min_hr_temp_08`,
    `min_hr_temp_09`,
    `min_hr_temp_10`,
    `min_hr_rain_01`,
    `min_hr_rain_02`,
    `min_hr_rain_03`,
    `min_hr_rain_04`,
    `min_hr_rain_05`,
    `min_hr_rain_06`,
    `min_hr_rain_07`,
    `min_hr_rain_08`,
    `min_hr_rain_09`,
    `min_hr_rain_10`,
    `min_max_heat_index`,
    `min_min_heat_index`,
    `min_heat_index`,
    `min_max_avg_windspeed_today`,
    `min_lightning_count_last_minute`,
    `min_last_lightning_time`,
    `min_last_lightning_date`,
    `min_avg_wind_direction`,
    `min_nexstorm_last_strike_distance`,
    `min_nexstorm_last_strike_bearing`,
    `min_extra_temp_sensor_7`,
    `min_extra_temp_sensor_8`,
    `min_extra_hum_sensor_4`,
    `min_extra_hum_sensor_5`,
    `min_extra_hum_sensor_6`,
    `min_extra_hum_sensor_7`,
    `min_extra_hum_sensor_8`,
    `min_vp_solar_wm2`,
    `min_max_in_temp`,
    `min_min_in_temp`,
    `min_apparent_temp`,
    `min_max_baro`,
    `min_min_baro`,
    `min_max_gust_last_hour`,
    `min_max_gust_last_hour_time`,
    `min_max_gust_today_time`,
    `min_max_apparent_temp`,
    `min_min_apparent_temp`,
    `min_max_dew_point`,
    `min_min_dew_point`,
    `min_max_gust_last_minute`,
    `min_current_year`,
    `min_thsw_index`,
    `min_temp_trend`,
    `min_humidity_trend`,
    `min_humidex_trend`,
    `min_hr_wind_dir_01`,
    `min_hr_wind_dir_02`,
    `min_hr_wind_dir_03`,
    `min_hr_wind_dir_04`,
    `min_hr_wind_dir_05`,
    `min_hr_wind_dir_06`,
    `min_hr_wind_dir_07`,
    `min_hr_wind_dir_08`,
    `min_hr_wind_dir_09`,
    `min_hr_wind_dir_10`,
    `min_leaf_wetness_vp`,
    `min_soil_moisture_vp`,
    `min_avg_wind_10min`,
    `min_wet_bulb_temp`,
    `min_latitude`,
    `min_longitude`,
    `min_rain_9am_reset`,
    `min_daily_high_humidity`,
    `min_daily_low_humidity`,
    `min_rain_midnight_reset`,
    `min_daily_low_windchill_time`,
    `min_cost_channel_1_watts`,
    `min_cost_channel_2_watts`,
    `min_cost_channel_3_watts`,
    `min_cost_channel_4_watts`,
    `min_cost_channel_5_watts`,
    `min_cost_channel_6_watts`,
    `min_daily_wind_run_km`,
    `min_daily_max_temp_time`,
    `min_daily_min_temp_time`,
    `min_avg_wind_dir_10min`,
    `min_firmware_version`
  ) SELECT
    yesterday,
    MIN(`station_id`),
    MIN(`average_windspeed`),
    MIN(`current_windspeed`),
    MIN(`wind_dir`),
    MIN(`out_temp`),
    MIN(`out_hum`),
    MIN(`barometer`),
    MIN(`day_rain`),
    MIN(`month_rain`),
    MIN(`year_rain`),
    MIN(`rain_rate_mm_min`),
    MIN(`rain_rate_max_mm_min`),
    MIN(`in_temp`),
    MIN(`in_hum`),
    MIN(`soil_temp`),
    MIN(`forecast_icon_code`),
    MIN(`wmr968_extra_temp`),
    MIN(`wmr968_extra_hum`),
    MIN(`wmr968_extra_sensor`),
    MIN(`yesterday_rain`),
    MIN(`extra_temp_sensor_1`),
    MIN(`extra_temp_sensor_2`),
    MIN(`extra_temp_sensor_3`),
    MIN(`extra_temp_sensor_4`),
    MIN(`extra_temp_sensor_5`),
    MIN(`extra_temp_sensor_6`),
    MIN(`extra_hum_sensor_1`),
    MIN(`extra_hum_sensor_2`),
    MIN(`extra_hum_sensor_3`),
    MIN(`measurement_hour`),
    MIN(`measurement_minute`),
    MIN(`measurement_second`),
    MIN(`location_label`),
    MIN(`lightning_count_since_noon`),
    MIN(`solar_percent_of_max`),
    MIN(`measurement_day`),
    MIN(`measurement_month`),
    MIN(`wmr968_batt1`),
    MIN(`wmr968_batt2`),
    MIN(`wmr968_batt3`),
    MIN(`wmr968_batt4`),
    MIN(`wmr968_batt5`),
    MIN(`wmr968_batt6`),
    MIN(`wmr968_batt7`),
    MIN(`wind_chill`),
    MIN(`humidex`),
    MIN(`max_temp_today`),
    MIN(`min_temp_today`),
    MIN(`current_condition_icon`),
    MIN(`sky_condition_text`),
    MIN(`baro_trend_last_hour`),
    MIN(`windspeed_hour_01`),
    MIN(`windspeed_hour_02`),
    MIN(`windspeed_hour_03`),
    MIN(`windspeed_hour_04`),
    MIN(`windspeed_hour_05`),
    MIN(`windspeed_hour_06`),
    MIN(`windspeed_hour_07`),
    MIN(`windspeed_hour_08`),
    MIN(`windspeed_hour_09`),
    MIN(`windspeed_hour_10`),
    MIN(`windspeed_hour_11`),
    MIN(`windspeed_hour_12`),
    MIN(`windspeed_hour_13`),
    MIN(`windspeed_hour_14`),
    MIN(`windspeed_hour_15`),
    MIN(`windspeed_hour_16`),
    MIN(`windspeed_hour_17`),
    MIN(`windspeed_hour_18`),
    MIN(`windspeed_hour_19`),
    MIN(`windspeed_hour_20`),
    MIN(`max_wind_gust`),
    MIN(`dew_point`),
    MIN(`cloud_height`),
    MIN(`current_date`),
    MIN(`max_humidex`),
    MIN(`min_humidex`),
    MIN(`max_windchill`),
    MIN(`min_windchill`),
    MIN(`uv_index`),
    MIN(`hr_windspeed_01`),
    MIN(`hr_windspeed_02`),
    MIN(`hr_windspeed_03`),
    MIN(`hr_windspeed_04`),
    MIN(`hr_windspeed_05`),
    MIN(`hr_windspeed_06`),
    MIN(`hr_windspeed_07`),
    MIN(`hr_windspeed_08`),
    MIN(`hr_windspeed_09`),
    MIN(`hr_windspeed_10`),
    MIN(`hr_temp_01`),
    MIN(`hr_temp_02`),
    MIN(`hr_temp_03`),
    MIN(`hr_temp_04`),
    MIN(`hr_temp_05`),
    MIN(`hr_temp_06`),
    MIN(`hr_temp_07`),
    MIN(`hr_temp_08`),
    MIN(`hr_temp_09`),
    MIN(`hr_temp_10`),
    MIN(`hr_rain_01`),
    MIN(`hr_rain_02`),
    MIN(`hr_rain_03`),
    MIN(`hr_rain_04`),
    MIN(`hr_rain_05`),
    MIN(`hr_rain_06`),
    MIN(`hr_rain_07`),
    MIN(`hr_rain_08`),
    MIN(`hr_rain_09`),
    MIN(`hr_rain_10`),
    MIN(`max_heat_index`),
    MIN(`min_heat_index`),
    MIN(`heat_index`),
    MIN(`max_avg_windspeed_today`),
    MIN(`lightning_count_last_minute`),
    MIN(`last_lightning_time`),
    MIN(`last_lightning_date`),
    MIN(`avg_wind_direction`),
    MIN(`nexstorm_last_strike_distance`),
    MIN(`nexstorm_last_strike_bearing`),
    MIN(`extra_temp_sensor_7`),
    MIN(`extra_temp_sensor_8`),
    MIN(`extra_hum_sensor_4`),
    MIN(`extra_hum_sensor_5`),
    MIN(`extra_hum_sensor_6`),
    MIN(`extra_hum_sensor_7`),
    MIN(`extra_hum_sensor_8`),
    MIN(`vp_solar_wm2`),
    MIN(`max_in_temp`),
    MIN(`min_in_temp`),
    MIN(`apparent_temp`),
    MIN(`max_baro`),
    MIN(`min_baro`),
    MIN(`max_gust_last_hour`),
    MIN(`max_gust_last_hour_time`),
    MIN(`max_gust_today_time`),
    MIN(`max_apparent_temp`),
    MIN(`min_apparent_temp`),
    MIN(`max_dew_point`),
    MIN(`min_dew_point`),
    MIN(`max_gust_last_minute`),
    MIN(`current_year`),
    MIN(`thsw_index`),
    MIN(`temp_trend`),
    MIN(`humidity_trend`),
    MIN(`humidex_trend`),
    MIN(`hr_wind_dir_01`),
    MIN(`hr_wind_dir_02`),
    MIN(`hr_wind_dir_03`),
    MIN(`hr_wind_dir_04`),
    MIN(`hr_wind_dir_05`),
    MIN(`hr_wind_dir_06`),
    MIN(`hr_wind_dir_07`),
    MIN(`hr_wind_dir_08`),
    MIN(`hr_wind_dir_09`),
    MIN(`hr_wind_dir_10`),
    MIN(`leaf_wetness_vp`),
    MIN(`soil_moisture_vp`),
    MIN(`avg_wind_10min`),
    MIN(`wet_bulb_temp`),
    MIN(`latitude`),
    MIN(`longitude`),
    MIN(`rain_9am_reset`),
    MIN(`daily_high_humidity`),
    MIN(`daily_low_humidity`),
    MIN(`rain_midnight_reset`),
    MIN(`daily_low_windchill_time`),
    MIN(`cost_channel_1_watts`),
    MIN(`cost_channel_2_watts`),
    MIN(`cost_channel_3_watts`),
    MIN(`cost_channel_4_watts`),
    MIN(`cost_channel_5_watts`),
    MIN(`cost_channel_6_watts`),
    MIN(`daily_wind_run_km`),
    MIN(`daily_max_temp_time`),
    MIN(`daily_min_temp_time`),
    MIN(`avg_wind_dir_10min`),
    MIN(`firmware_version`)
  FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) = yesterday
  ON DUPLICATE KEY UPDATE
    min_station_id = VALUES(min_station_id),
    min_average_windspeed = VALUES(min_average_windspeed),
    min_current_windspeed = VALUES(min_current_windspeed),
    min_wind_dir = VALUES(min_wind_dir),
    min_out_temp = VALUES(min_out_temp),
    min_out_hum = VALUES(min_out_hum),
    min_barometer = VALUES(min_barometer),
    min_day_rain = VALUES(min_day_rain),
    min_month_rain = VALUES(min_month_rain),
    min_year_rain = VALUES(min_year_rain),
    min_rain_rate_mm_min = VALUES(min_rain_rate_mm_min),
    min_rain_rate_max_mm_min = VALUES(min_rain_rate_max_mm_min),
    min_in_temp = VALUES(min_in_temp),
    min_in_hum = VALUES(min_in_hum),
    min_soil_temp = VALUES(min_soil_temp),
    min_forecast_icon_code = VALUES(min_forecast_icon_code),
    min_wmr968_extra_temp = VALUES(min_wmr968_extra_temp),
    min_wmr968_extra_hum = VALUES(min_wmr968_extra_hum),
    min_wmr968_extra_sensor = VALUES(min_wmr968_extra_sensor),
    min_yesterday_rain = VALUES(min_yesterday_rain),
    min_extra_temp_sensor_1 = VALUES(min_extra_temp_sensor_1),
    min_extra_temp_sensor_2 = VALUES(min_extra_temp_sensor_2),
    min_extra_temp_sensor_3 = VALUES(min_extra_temp_sensor_3),
    min_extra_temp_sensor_4 = VALUES(min_extra_temp_sensor_4),
    min_extra_temp_sensor_5 = VALUES(min_extra_temp_sensor_5),
    min_extra_temp_sensor_6 = VALUES(min_extra_temp_sensor_6),
    min_extra_hum_sensor_1 = VALUES(min_extra_hum_sensor_1),
    min_extra_hum_sensor_2 = VALUES(min_extra_hum_sensor_2),
    min_extra_hum_sensor_3 = VALUES(min_extra_hum_sensor_3),
    min_measurement_hour = VALUES(min_measurement_hour),
    min_measurement_minute = VALUES(min_measurement_minute),
    min_measurement_second = VALUES(min_measurement_second),
    min_location_label = VALUES(min_location_label),
    min_lightning_count_since_noon = VALUES(min_lightning_count_since_noon),
    min_solar_percent_of_max = VALUES(min_solar_percent_of_max),
    min_measurement_day = VALUES(min_measurement_day),
    min_measurement_month = VALUES(min_measurement_month),
    min_wmr968_batt1 = VALUES(min_wmr968_batt1),
    min_wmr968_batt2 = VALUES(min_wmr968_batt2),
    min_wmr968_batt3 = VALUES(min_wmr968_batt3),
    min_wmr968_batt4 = VALUES(min_wmr968_batt4),
    min_wmr968_batt5 = VALUES(min_wmr968_batt5),
    min_wmr968_batt6 = VALUES(min_wmr968_batt6),
    min_wmr968_batt7 = VALUES(min_wmr968_batt7),
    min_wind_chill = VALUES(min_wind_chill),
    min_humidex = VALUES(min_humidex),
    min_max_temp_today = VALUES(min_max_temp_today),
    min_min_temp_today = VALUES(min_min_temp_today),
    min_current_condition_icon = VALUES(min_current_condition_icon),
    min_sky_condition_text = VALUES(min_sky_condition_text),
    min_baro_trend_last_hour = VALUES(min_baro_trend_last_hour),
    min_windspeed_hour_01 = VALUES(min_windspeed_hour_01),
    min_windspeed_hour_02 = VALUES(min_windspeed_hour_02),
    min_windspeed_hour_03 = VALUES(min_windspeed_hour_03),
    min_windspeed_hour_04 = VALUES(min_windspeed_hour_04),
    min_windspeed_hour_05 = VALUES(min_windspeed_hour_05),
    min_windspeed_hour_06 = VALUES(min_windspeed_hour_06),
    min_windspeed_hour_07 = VALUES(min_windspeed_hour_07),
    min_windspeed_hour_08 = VALUES(min_windspeed_hour_08),
    min_windspeed_hour_09 = VALUES(min_windspeed_hour_09),
    min_windspeed_hour_10 = VALUES(min_windspeed_hour_10),
    min_windspeed_hour_11 = VALUES(min_windspeed_hour_11),
    min_windspeed_hour_12 = VALUES(min_windspeed_hour_12),
    min_windspeed_hour_13 = VALUES(min_windspeed_hour_13),
    min_windspeed_hour_14 = VALUES(min_windspeed_hour_14),
    min_windspeed_hour_15 = VALUES(min_windspeed_hour_15),
    min_windspeed_hour_16 = VALUES(min_windspeed_hour_16),
    min_windspeed_hour_17 = VALUES(min_windspeed_hour_17),
    min_windspeed_hour_18 = VALUES(min_windspeed_hour_18),
    min_windspeed_hour_19 = VALUES(min_windspeed_hour_19),
    min_windspeed_hour_20 = VALUES(min_windspeed_hour_20),
    min_max_wind_gust = VALUES(min_max_wind_gust),
    min_dew_point = VALUES(min_dew_point),
    min_cloud_height = VALUES(min_cloud_height),
    min_current_date = VALUES(min_current_date),
    min_max_humidex = VALUES(min_max_humidex),
    min_min_humidex = VALUES(min_min_humidex),
    min_max_windchill = VALUES(min_max_windchill),
    min_min_windchill = VALUES(min_min_windchill),
    min_uv_index = VALUES(min_uv_index),
    min_hr_windspeed_01 = VALUES(min_hr_windspeed_01),
    min_hr_windspeed_02 = VALUES(min_hr_windspeed_02),
    min_hr_windspeed_03 = VALUES(min_hr_windspeed_03),
    min_hr_windspeed_04 = VALUES(min_hr_windspeed_04),
    min_hr_windspeed_05 = VALUES(min_hr_windspeed_05),
    min_hr_windspeed_06 = VALUES(min_hr_windspeed_06),
    min_hr_windspeed_07 = VALUES(min_hr_windspeed_07),
    min_hr_windspeed_08 = VALUES(min_hr_windspeed_08),
    min_hr_windspeed_09 = VALUES(min_hr_windspeed_09),
    min_hr_windspeed_10 = VALUES(min_hr_windspeed_10),
    min_hr_temp_01 = VALUES(min_hr_temp_01),
    min_hr_temp_02 = VALUES(min_hr_temp_02),
    min_hr_temp_03 = VALUES(min_hr_temp_03),
    min_hr_temp_04 = VALUES(min_hr_temp_04),
    min_hr_temp_05 = VALUES(min_hr_temp_05),
    min_hr_temp_06 = VALUES(min_hr_temp_06),
    min_hr_temp_07 = VALUES(min_hr_temp_07),
    min_hr_temp_08 = VALUES(min_hr_temp_08),
    min_hr_temp_09 = VALUES(min_hr_temp_09),
    min_hr_temp_10 = VALUES(min_hr_temp_10),
    min_hr_rain_01 = VALUES(min_hr_rain_01),
    min_hr_rain_02 = VALUES(min_hr_rain_02),
    min_hr_rain_03 = VALUES(min_hr_rain_03),
    min_hr_rain_04 = VALUES(min_hr_rain_04),
    min_hr_rain_05 = VALUES(min_hr_rain_05),
    min_hr_rain_06 = VALUES(min_hr_rain_06),
    min_hr_rain_07 = VALUES(min_hr_rain_07),
    min_hr_rain_08 = VALUES(min_hr_rain_08),
    min_hr_rain_09 = VALUES(min_hr_rain_09),
    min_hr_rain_10 = VALUES(min_hr_rain_10),
    min_max_heat_index = VALUES(min_max_heat_index),
    min_min_heat_index = VALUES(min_min_heat_index),
    min_heat_index = VALUES(min_heat_index),
    min_max_avg_windspeed_today = VALUES(min_max_avg_windspeed_today),
    min_lightning_count_last_minute = VALUES(min_lightning_count_last_minute),
    min_last_lightning_time = VALUES(min_last_lightning_time),
    min_last_lightning_date = VALUES(min_last_lightning_date),
    min_avg_wind_direction = VALUES(min_avg_wind_direction),
    min_nexstorm_last_strike_distance = VALUES(min_nexstorm_last_strike_distance),
    min_nexstorm_last_strike_bearing = VALUES(min_nexstorm_last_strike_bearing),
    min_extra_temp_sensor_7 = VALUES(min_extra_temp_sensor_7),
    min_extra_temp_sensor_8 = VALUES(min_extra_temp_sensor_8),
    min_extra_hum_sensor_4 = VALUES(min_extra_hum_sensor_4),
    min_extra_hum_sensor_5 = VALUES(min_extra_hum_sensor_5),
    min_extra_hum_sensor_6 = VALUES(min_extra_hum_sensor_6),
    min_extra_hum_sensor_7 = VALUES(min_extra_hum_sensor_7),
    min_extra_hum_sensor_8 = VALUES(min_extra_hum_sensor_8),
    min_vp_solar_wm2 = VALUES(min_vp_solar_wm2),
    min_max_in_temp = VALUES(min_max_in_temp),
    min_min_in_temp = VALUES(min_min_in_temp),
    min_apparent_temp = VALUES(min_apparent_temp),
    min_max_baro = VALUES(min_max_baro),
    min_min_baro = VALUES(min_min_baro),
    min_max_gust_last_hour = VALUES(min_max_gust_last_hour),
    min_max_gust_last_hour_time = VALUES(min_max_gust_last_hour_time),
    min_max_gust_today_time = VALUES(min_max_gust_today_time),
    min_max_apparent_temp = VALUES(min_max_apparent_temp),
    min_min_apparent_temp = VALUES(min_min_apparent_temp),
    min_max_dew_point = VALUES(min_max_dew_point),
    min_min_dew_point = VALUES(min_min_dew_point),
    min_max_gust_last_minute = VALUES(min_max_gust_last_minute),
    min_current_year = VALUES(min_current_year),
    min_thsw_index = VALUES(min_thsw_index),
    min_temp_trend = VALUES(min_temp_trend),
    min_humidity_trend = VALUES(min_humidity_trend),
    min_humidex_trend = VALUES(min_humidex_trend),
    min_hr_wind_dir_01 = VALUES(min_hr_wind_dir_01),
    min_hr_wind_dir_02 = VALUES(min_hr_wind_dir_02),
    min_hr_wind_dir_03 = VALUES(min_hr_wind_dir_03),
    min_hr_wind_dir_04 = VALUES(min_hr_wind_dir_04),
    min_hr_wind_dir_05 = VALUES(min_hr_wind_dir_05),
    min_hr_wind_dir_06 = VALUES(min_hr_wind_dir_06),
    min_hr_wind_dir_07 = VALUES(min_hr_wind_dir_07),
    min_hr_wind_dir_08 = VALUES(min_hr_wind_dir_08),
    min_hr_wind_dir_09 = VALUES(min_hr_wind_dir_09),
    min_hr_wind_dir_10 = VALUES(min_hr_wind_dir_10),
    min_leaf_wetness_vp = VALUES(min_leaf_wetness_vp),
    min_soil_moisture_vp = VALUES(min_soil_moisture_vp),
    min_avg_wind_10min = VALUES(min_avg_wind_10min),
    min_wet_bulb_temp = VALUES(min_wet_bulb_temp),
    min_latitude = VALUES(min_latitude),
    min_longitude = VALUES(min_longitude),
    min_rain_9am_reset = VALUES(min_rain_9am_reset),
    min_daily_high_humidity = VALUES(min_daily_high_humidity),
    min_daily_low_humidity = VALUES(min_daily_low_humidity),
    min_rain_midnight_reset = VALUES(min_rain_midnight_reset),
    min_daily_low_windchill_time = VALUES(min_daily_low_windchill_time),
    min_cost_channel_1_watts = VALUES(min_cost_channel_1_watts),
    min_cost_channel_2_watts = VALUES(min_cost_channel_2_watts),
    min_cost_channel_3_watts = VALUES(min_cost_channel_3_watts),
    min_cost_channel_4_watts = VALUES(min_cost_channel_4_watts),
    min_cost_channel_5_watts = VALUES(min_cost_channel_5_watts),
    min_cost_channel_6_watts = VALUES(min_cost_channel_6_watts),
    min_daily_wind_run_km = VALUES(min_daily_wind_run_km),
    min_daily_max_temp_time = VALUES(min_daily_max_temp_time),
    min_daily_min_temp_time = VALUES(min_daily_min_temp_time),
    min_avg_wind_dir_10min = VALUES(min_avg_wind_dir_10min),
    min_firmware_version = VALUES(min_firmware_version);

  -- Insert avg values for yesterday
  INSERT INTO weather_daily_avg (
    `date`,
    `avg_station_id`,
    `avg_average_windspeed`,
    `avg_current_windspeed`,
    `avg_wind_dir`,
    `avg_out_temp`,
    `avg_out_hum`,
    `avg_barometer`,
    `avg_day_rain`,
    `avg_month_rain`,
    `avg_year_rain`,
    `avg_rain_rate_mm_min`,
    `avg_rain_rate_max_mm_min`,
    `avg_in_temp`,
    `avg_in_hum`,
    `avg_soil_temp`,
    `avg_forecast_icon_code`,
    `avg_wmr968_extra_temp`,
    `avg_wmr968_extra_hum`,
    `avg_wmr968_extra_sensor`,
    `avg_yesterday_rain`,
    `avg_extra_temp_sensor_1`,
    `avg_extra_temp_sensor_2`,
    `avg_extra_temp_sensor_3`,
    `avg_extra_temp_sensor_4`,
    `avg_extra_temp_sensor_5`,
    `avg_extra_temp_sensor_6`,
    `avg_extra_hum_sensor_1`,
    `avg_extra_hum_sensor_2`,
    `avg_extra_hum_sensor_3`,
    `avg_measurement_hour`,
    `avg_measurement_minute`,
    `avg_measurement_second`,
    `avg_location_label`,
    `avg_lightning_count_since_noon`,
    `avg_solar_percent_of_max`,
    `avg_measurement_day`,
    `avg_measurement_month`,
    `avg_wmr968_batt1`,
    `avg_wmr968_batt2`,
    `avg_wmr968_batt3`,
    `avg_wmr968_batt4`,
    `avg_wmr968_batt5`,
    `avg_wmr968_batt6`,
    `avg_wmr968_batt7`,
    `avg_wind_chill`,
    `avg_humidex`,
    `avg_max_temp_today`,
    `avg_min_temp_today`,
    `avg_current_condition_icon`,
    `avg_sky_condition_text`,
    `avg_baro_trend_last_hour`,
    `avg_windspeed_hour_01`,
    `avg_windspeed_hour_02`,
    `avg_windspeed_hour_03`,
    `avg_windspeed_hour_04`,
    `avg_windspeed_hour_05`,
    `avg_windspeed_hour_06`,
    `avg_windspeed_hour_07`,
    `avg_windspeed_hour_08`,
    `avg_windspeed_hour_09`,
    `avg_windspeed_hour_10`,
    `avg_windspeed_hour_11`,
    `avg_windspeed_hour_12`,
    `avg_windspeed_hour_13`,
    `avg_windspeed_hour_14`,
    `avg_windspeed_hour_15`,
    `avg_windspeed_hour_16`,
    `avg_windspeed_hour_17`,
    `avg_windspeed_hour_18`,
    `avg_windspeed_hour_19`,
    `avg_windspeed_hour_20`,
    `avg_max_wind_gust`,
    `avg_dew_point`,
    `avg_cloud_height`,
    `avg_current_date`,
    `avg_max_humidex`,
    `avg_min_humidex`,
    `avg_max_windchill`,
    `avg_min_windchill`,
    `avg_uv_index`,
    `avg_hr_windspeed_01`,
    `avg_hr_windspeed_02`,
    `avg_hr_windspeed_03`,
    `avg_hr_windspeed_04`,
    `avg_hr_windspeed_05`,
    `avg_hr_windspeed_06`,
    `avg_hr_windspeed_07`,
    `avg_hr_windspeed_08`,
    `avg_hr_windspeed_09`,
    `avg_hr_windspeed_10`,
    `avg_hr_temp_01`,
    `avg_hr_temp_02`,
    `avg_hr_temp_03`,
    `avg_hr_temp_04`,
    `avg_hr_temp_05`,
    `avg_hr_temp_06`,
    `avg_hr_temp_07`,
    `avg_hr_temp_08`,
    `avg_hr_temp_09`,
    `avg_hr_temp_10`,
    `avg_hr_rain_01`,
    `avg_hr_rain_02`,
    `avg_hr_rain_03`,
    `avg_hr_rain_04`,
    `avg_hr_rain_05`,
    `avg_hr_rain_06`,
    `avg_hr_rain_07`,
    `avg_hr_rain_08`,
    `avg_hr_rain_09`,
    `avg_hr_rain_10`,
    `avg_max_heat_index`,
    `avg_min_heat_index`,
    `avg_heat_index`,
    `avg_max_avg_windspeed_today`,
    `avg_lightning_count_last_minute`,
    `avg_last_lightning_time`,
    `avg_last_lightning_date`,
    `avg_avg_wind_direction`,
    `avg_nexstorm_last_strike_distance`,
    `avg_nexstorm_last_strike_bearing`,
    `avg_extra_temp_sensor_7`,
    `avg_extra_temp_sensor_8`,
    `avg_extra_hum_sensor_4`,
    `avg_extra_hum_sensor_5`,
    `avg_extra_hum_sensor_6`,
    `avg_extra_hum_sensor_7`,
    `avg_extra_hum_sensor_8`,
    `avg_vp_solar_wm2`,
    `avg_max_in_temp`,
    `avg_min_in_temp`,
    `avg_apparent_temp`,
    `avg_max_baro`,
    `avg_min_baro`,
    `avg_max_gust_last_hour`,
    `avg_max_gust_last_hour_time`,
    `avg_max_gust_today_time`,
    `avg_max_apparent_temp`,
    `avg_min_apparent_temp`,
    `avg_max_dew_point`,
    `avg_min_dew_point`,
    `avg_max_gust_last_minute`,
    `avg_current_year`,
    `avg_thsw_index`,
    `avg_temp_trend`,
    `avg_humidity_trend`,
    `avg_humidex_trend`,
    `avg_hr_wind_dir_01`,
    `avg_hr_wind_dir_02`,
    `avg_hr_wind_dir_03`,
    `avg_hr_wind_dir_04`,
    `avg_hr_wind_dir_05`,
    `avg_hr_wind_dir_06`,
    `avg_hr_wind_dir_07`,
    `avg_hr_wind_dir_08`,
    `avg_hr_wind_dir_09`,
    `avg_hr_wind_dir_10`,
    `avg_leaf_wetness_vp`,
    `avg_soil_moisture_vp`,
    `avg_avg_wind_10min`,
    `avg_wet_bulb_temp`,
    `avg_latitude`,
    `avg_longitude`,
    `avg_rain_9am_reset`,
    `avg_daily_high_humidity`,
    `avg_daily_low_humidity`,
    `avg_rain_midnight_reset`,
    `avg_daily_low_windchill_time`,
    `avg_cost_channel_1_watts`,
    `avg_cost_channel_2_watts`,
    `avg_cost_channel_3_watts`,
    `avg_cost_channel_4_watts`,
    `avg_cost_channel_5_watts`,
    `avg_cost_channel_6_watts`,
    `avg_daily_wind_run_km`,
    `avg_daily_max_temp_time`,
    `avg_daily_min_temp_time`,
    `avg_avg_wind_dir_10min`,
    `avg_firmware_version`
  ) SELECT
    yesterday,
    AVG(`station_id`),
    AVG(`average_windspeed`),
    AVG(`current_windspeed`),
    AVG(`wind_dir`),
    AVG(`out_temp`),
    AVG(`out_hum`),
    AVG(`barometer`),
    AVG(`day_rain`),
    AVG(`month_rain`),
    AVG(`year_rain`),
    AVG(`rain_rate_mm_min`),
    AVG(`rain_rate_max_mm_min`),
    AVG(`in_temp`),
    AVG(`in_hum`),
    AVG(`soil_temp`),
    AVG(`forecast_icon_code`),
    AVG(`wmr968_extra_temp`),
    AVG(`wmr968_extra_hum`),
    AVG(`wmr968_extra_sensor`),
    AVG(`yesterday_rain`),
    AVG(`extra_temp_sensor_1`),
    AVG(`extra_temp_sensor_2`),
    AVG(`extra_temp_sensor_3`),
    AVG(`extra_temp_sensor_4`),
    AVG(`extra_temp_sensor_5`),
    AVG(`extra_temp_sensor_6`),
    AVG(`extra_hum_sensor_1`),
    AVG(`extra_hum_sensor_2`),
    AVG(`extra_hum_sensor_3`),
    AVG(`measurement_hour`),
    AVG(`measurement_minute`),
    AVG(`measurement_second`),
    MAX(`location_label`),  -- MAX for strings
    AVG(`lightning_count_since_noon`),
    AVG(`solar_percent_of_max`),
    AVG(`measurement_day`),
    AVG(`measurement_month`),
    AVG(`wmr968_batt1`),
    AVG(`wmr968_batt2`),
    AVG(`wmr968_batt3`),
    AVG(`wmr968_batt4`),
    AVG(`wmr968_batt5`),
    AVG(`wmr968_batt6`),
    AVG(`wmr968_batt7`),
    AVG(`wind_chill`),
    AVG(`humidex`),
    AVG(`max_temp_today`),
    AVG(`min_temp_today`),
    AVG(`current_condition_icon`),
    MAX(`sky_condition_text`),
    AVG(`baro_trend_last_hour`),
    AVG(`windspeed_hour_01`),
    AVG(`windspeed_hour_02`),
    AVG(`windspeed_hour_03`),
    AVG(`windspeed_hour_04`),
    AVG(`windspeed_hour_05`),
    AVG(`windspeed_hour_06`),
    AVG(`windspeed_hour_07`),
    AVG(`windspeed_hour_08`),
    AVG(`windspeed_hour_09`),
    AVG(`windspeed_hour_10`),
    AVG(`windspeed_hour_11`),
    AVG(`windspeed_hour_12`),
    AVG(`windspeed_hour_13`),
    AVG(`windspeed_hour_14`),
    AVG(`windspeed_hour_15`),
    AVG(`windspeed_hour_16`),
    AVG(`windspeed_hour_17`),
    AVG(`windspeed_hour_18`),
    AVG(`windspeed_hour_19`),
    AVG(`windspeed_hour_20`),
    AVG(`max_wind_gust`),
    AVG(`dew_point`),
    AVG(`cloud_height`),
    MAX(`current_date`),
    AVG(`max_humidex`),
    AVG(`min_humidex`),
    AVG(`max_windchill`),
    AVG(`min_windchill`),
    AVG(`uv_index`),
    AVG(`hr_windspeed_01`),
    AVG(`hr_windspeed_02`),
    AVG(`hr_windspeed_03`),
    AVG(`hr_windspeed_04`),
    AVG(`hr_windspeed_05`),
    AVG(`hr_windspeed_06`),
    AVG(`hr_windspeed_07`),
    AVG(`hr_windspeed_08`),
    AVG(`hr_windspeed_09`),
    AVG(`hr_windspeed_10`),
    AVG(`hr_temp_01`),
    AVG(`hr_temp_02`),
    AVG(`hr_temp_03`),
    AVG(`hr_temp_04`),
    AVG(`hr_temp_05`),
    AVG(`hr_temp_06`),
    AVG(`hr_temp_07`),
    AVG(`hr_temp_08`),
    AVG(`hr_temp_09`),
    AVG(`hr_temp_10`),
    AVG(`hr_rain_01`),
    AVG(`hr_rain_02`),
    AVG(`hr_rain_03`),
    AVG(`hr_rain_04`),
    AVG(`hr_rain_05`),
    AVG(`hr_rain_06`),
    AVG(`hr_rain_07`),
    AVG(`hr_rain_08`),
    AVG(`hr_rain_09`),
    AVG(`hr_rain_10`),
    AVG(`max_heat_index`),
    AVG(`min_heat_index`),
    AVG(`heat_index`),
    AVG(`max_avg_windspeed_today`),
    AVG(`lightning_count_last_minute`),
    MAX(`last_lightning_time`),
    MAX(`last_lightning_date`),
    AVG(`avg_wind_direction`),
    AVG(`nexstorm_last_strike_distance`),
    AVG(`nexstorm_last_strike_bearing`),
    AVG(`extra_temp_sensor_7`),
    AVG(`extra_temp_sensor_8`),
    AVG(`extra_hum_sensor_4`),
    AVG(`extra_hum_sensor_5`),
    AVG(`extra_hum_sensor_6`),
    AVG(`extra_hum_sensor_7`),
    AVG(`extra_hum_sensor_8`),
    AVG(`vp_solar_wm2`),
    AVG(`max_in_temp`),
    AVG(`min_in_temp`),
    AVG(`apparent_temp`),
    AVG(`max_baro`),
    AVG(`min_baro`),
    AVG(`max_gust_last_hour`),
    MAX(`max_gust_last_hour_time`),
    MAX(`max_gust_today_time`),
    AVG(`max_apparent_temp`),
    AVG(`min_apparent_temp`),
    AVG(`max_dew_point`),
    AVG(`min_dew_point`),
    AVG(`max_gust_last_minute`),
    AVG(`current_year`),
    AVG(`thsw_index`),
    AVG(`temp_trend`),
    AVG(`humidity_trend`),
    AVG(`humidex_trend`),
    AVG(`hr_wind_dir_01`),
    AVG(`hr_wind_dir_02`),
    AVG(`hr_wind_dir_03`),
    AVG(`hr_wind_dir_04`),
    AVG(`hr_wind_dir_05`),
    AVG(`hr_wind_dir_06`),
    AVG(`hr_wind_dir_07`),
    AVG(`hr_wind_dir_08`),
    AVG(`hr_wind_dir_09`),
    AVG(`hr_wind_dir_10`),
    AVG(`leaf_wetness_vp`),
    AVG(`soil_moisture_vp`),
    AVG(`avg_wind_10min`),
    AVG(`wet_bulb_temp`),
    AVG(`latitude`),
    AVG(`longitude`),
    AVG(`rain_9am_reset`),
    AVG(`daily_high_humidity`),
    AVG(`daily_low_humidity`),
    AVG(`rain_midnight_reset`),
    MAX(`daily_low_windchill_time`),
    AVG(`cost_channel_1_watts`),
    AVG(`cost_channel_2_watts`),
    AVG(`cost_channel_3_watts`),
    AVG(`cost_channel_4_watts`),
    AVG(`cost_channel_5_watts`),
    AVG(`cost_channel_6_watts`),
    AVG(`daily_wind_run_km`),
    MAX(`daily_max_temp_time`),
    MAX(`daily_min_temp_time`),
    AVG(`avg_wind_dir_10min`),
    MAX(`firmware_version`)
  FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) = yesterday
  ON DUPLICATE KEY UPDATE
    avg_station_id = VALUES(avg_station_id),
    avg_average_windspeed = VALUES(avg_average_windspeed),
    avg_current_windspeed = VALUES(avg_current_windspeed),
    avg_wind_dir = VALUES(avg_wind_dir),
    avg_out_temp = VALUES(avg_out_temp),
    avg_out_hum = VALUES(avg_out_hum),
    avg_barometer = VALUES(avg_barometer),
    avg_day_rain = VALUES(avg_day_rain),
    avg_month_rain = VALUES(avg_month_rain),
    avg_year_rain = VALUES(avg_year_rain),
    avg_rain_rate_mm_min = VALUES(avg_rain_rate_mm_min),
    avg_rain_rate_max_mm_min = VALUES(avg_rain_rate_max_mm_min),
    avg_in_temp = VALUES(avg_in_temp),
    avg_in_hum = VALUES(avg_in_hum),
    avg_soil_temp = VALUES(avg_soil_temp),
    avg_forecast_icon_code = VALUES(avg_forecast_icon_code),
    avg_wmr968_extra_temp = VALUES(avg_wmr968_extra_temp),
    avg_wmr968_extra_hum = VALUES(avg_wmr968_extra_hum),
    avg_wmr968_extra_sensor = VALUES(avg_wmr968_extra_sensor),
    avg_yesterday_rain = VALUES(avg_yesterday_rain),
    avg_extra_temp_sensor_1 = VALUES(avg_extra_temp_sensor_1),
    avg_extra_temp_sensor_2 = VALUES(avg_extra_temp_sensor_2),
    avg_extra_temp_sensor_3 = VALUES(avg_extra_temp_sensor_3),
    avg_extra_temp_sensor_4 = VALUES(avg_extra_temp_sensor_4),
    avg_extra_temp_sensor_5 = VALUES(avg_extra_temp_sensor_5),
    avg_extra_temp_sensor_6 = VALUES(avg_extra_temp_sensor_6),
    avg_extra_hum_sensor_1 = VALUES(avg_extra_hum_sensor_1),
    avg_extra_hum_sensor_2 = VALUES(avg_extra_hum_sensor_2),
    avg_extra_hum_sensor_3 = VALUES(avg_extra_hum_sensor_3),
    avg_measurement_hour = VALUES(avg_measurement_hour),
    avg_measurement_minute = VALUES(avg_measurement_minute),
    avg_measurement_second = VALUES(avg_measurement_second),
    avg_location_label = VALUES(avg_location_label),
    avg_lightning_count_since_noon = VALUES(avg_lightning_count_since_noon),
    avg_solar_percent_of_max = VALUES(avg_solar_percent_of_max),
    avg_measurement_day = VALUES(avg_measurement_day),
    avg_measurement_month = VALUES(avg_measurement_month),
    avg_wmr968_batt1 = VALUES(avg_wmr968_batt1),
    avg_wmr968_batt2 = VALUES(avg_wmr968_batt2),
    avg_wmr968_batt3 = VALUES(avg_wmr968_batt3),
    avg_wmr968_batt4 = VALUES(avg_wmr968_batt4),
    avg_wmr968_batt5 = VALUES(avg_wmr968_batt5),
    avg_wmr968_batt6 = VALUES(avg_wmr968_batt6),
    avg_wmr968_batt7 = VALUES(avg_wmr968_batt7),
    avg_wind_chill = VALUES(avg_wind_chill),
    avg_humidex = VALUES(avg_humidex),
    avg_max_temp_today = VALUES(avg_max_temp_today),
    avg_min_temp_today = VALUES(avg_min_temp_today),
    avg_current_condition_icon = VALUES(avg_current_condition_icon),
    avg_sky_condition_text = VALUES(avg_sky_condition_text),
    avg_baro_trend_last_hour = VALUES(avg_baro_trend_last_hour),
    avg_windspeed_hour_01 = VALUES(avg_windspeed_hour_01),
    avg_windspeed_hour_02 = VALUES(avg_windspeed_hour_02),
    avg_windspeed_hour_03 = VALUES(avg_windspeed_hour_03),
    avg_windspeed_hour_04 = VALUES(avg_windspeed_hour_04),
    avg_windspeed_hour_05 = VALUES(avg_windspeed_hour_05),
    avg_windspeed_hour_06 = VALUES(avg_windspeed_hour_06),
    avg_windspeed_hour_07 = VALUES(avg_windspeed_hour_07),
    avg_windspeed_hour_08 = VALUES(avg_windspeed_hour_08),
    avg_windspeed_hour_09 = VALUES(avg_windspeed_hour_09),
    avg_windspeed_hour_10 = VALUES(avg_windspeed_hour_10),
    avg_windspeed_hour_11 = VALUES(avg_windspeed_hour_11),
    avg_windspeed_hour_12 = VALUES(avg_windspeed_hour_12),
    avg_windspeed_hour_13 = VALUES(avg_windspeed_hour_13),
    avg_windspeed_hour_14 = VALUES(avg_windspeed_hour_14),
    avg_windspeed_hour_15 = VALUES(avg_windspeed_hour_15),
    avg_windspeed_hour_16 = VALUES(avg_windspeed_hour_16),
    avg_windspeed_hour_17 = VALUES(avg_windspeed_hour_17),
    avg_windspeed_hour_18 = VALUES(avg_windspeed_hour_18),
    avg_windspeed_hour_19 = VALUES(avg_windspeed_hour_19),
    avg_windspeed_hour_20 = VALUES(avg_windspeed_hour_20),
    avg_max_wind_gust = VALUES(avg_max_wind_gust),
    avg_dew_point = VALUES(avg_dew_point),
    avg_cloud_height = VALUES(avg_cloud_height),
    avg_current_date = VALUES(avg_current_date),
    avg_max_humidex = VALUES(avg_max_humidex),
    avg_min_humidex = VALUES(avg_min_humidex),
    avg_max_windchill = VALUES(avg_max_windchill),
    avg_min_windchill = VALUES(avg_min_windchill),
    avg_uv_index = VALUES(avg_uv_index),
    avg_hr_windspeed_01 = VALUES(avg_hr_windspeed_01),
    avg_hr_windspeed_02 = VALUES(avg_hr_windspeed_02),
    avg_hr_windspeed_03 = VALUES(avg_hr_windspeed_03),
    avg_hr_windspeed_04 = VALUES(avg_hr_windspeed_04),
    avg_hr_windspeed_05 = VALUES(avg_hr_windspeed_05),
    avg_hr_windspeed_06 = VALUES(avg_hr_windspeed_06),
    avg_hr_windspeed_07 = VALUES(avg_hr_windspeed_07),
    avg_hr_windspeed_08 = VALUES(avg_hr_windspeed_08),
    avg_hr_windspeed_09 = VALUES(avg_hr_windspeed_09),
    avg_hr_windspeed_10 = VALUES(avg_hr_windspeed_10),
    avg_hr_temp_01 = VALUES(avg_hr_temp_01),
    avg_hr_temp_02 = VALUES(avg_hr_temp_02),
    avg_hr_temp_03 = VALUES(avg_hr_temp_03),
    avg_hr_temp_04 = VALUES(avg_hr_temp_04),
    avg_hr_temp_05 = VALUES(avg_hr_temp_05),
    avg_hr_temp_06 = VALUES(avg_hr_temp_06),
    avg_hr_temp_07 = VALUES(avg_hr_temp_07),
    avg_hr_temp_08 = VALUES(avg_hr_temp_08),
    avg_hr_temp_09 = VALUES(avg_hr_temp_09),
    avg_hr_temp_10 = VALUES(avg_hr_temp_10),
    avg_hr_rain_01 = VALUES(avg_hr_rain_01),
    avg_hr_rain_02 = VALUES(avg_hr_rain_02),
    avg_hr_rain_03 = VALUES(avg_hr_rain_03),
    avg_hr_rain_04 = VALUES(avg_hr_rain_04),
    avg_hr_rain_05 = VALUES(avg_hr_rain_05),
    avg_hr_rain_06 = VALUES(avg_hr_rain_06),
    avg_hr_rain_07 = VALUES(avg_hr_rain_07),
    avg_hr_rain_08 = VALUES(avg_hr_rain_08),
    avg_hr_rain_09 = VALUES(avg_hr_rain_09),
    avg_hr_rain_10 = VALUES(avg_hr_rain_10),
    avg_max_heat_index = VALUES(avg_max_heat_index),
    avg_min_heat_index = VALUES(avg_min_heat_index),
    avg_heat_index = VALUES(avg_heat_index),
    avg_max_avg_windspeed_today = VALUES(avg_max_avg_windspeed_today),
    avg_lightning_count_last_minute = VALUES(avg_lightning_count_last_minute),
    avg_last_lightning_time = VALUES(avg_last_lightning_time),
    avg_last_lightning_date = VALUES(avg_last_lightning_date),
    avg_avg_wind_direction = VALUES(avg_avg_wind_direction),
    avg_nexstorm_last_strike_distance = VALUES(avg_nexstorm_last_strike_distance),
    avg_nexstorm_last_strike_bearing = VALUES(avg_nexstorm_last_strike_bearing),
    avg_extra_temp_sensor_7 = VALUES(avg_extra_temp_sensor_7),
    avg_extra_temp_sensor_8 = VALUES(avg_extra_temp_sensor_8),
    avg_extra_hum_sensor_4 = VALUES(avg_extra_hum_sensor_4),
    avg_extra_hum_sensor_5 = VALUES(avg_extra_hum_sensor_5),
    avg_extra_hum_sensor_6 = VALUES(avg_extra_hum_sensor_6),
    avg_extra_hum_sensor_7 = VALUES(avg_extra_hum_sensor_7),
    avg_extra_hum_sensor_8 = VALUES(avg_extra_hum_sensor_8),
    avg_vp_solar_wm2 = VALUES(avg_vp_solar_wm2),
    avg_max_in_temp = VALUES(avg_max_in_temp),
    avg_min_in_temp = VALUES(avg_min_in_temp),
    avg_apparent_temp = VALUES(avg_apparent_temp),
    avg_max_baro = VALUES(avg_max_baro),
    avg_min_baro = VALUES(avg_min_baro),
    avg_max_gust_last_hour = VALUES(avg_max_gust_last_hour),
    avg_max_gust_last_hour_time = VALUES(avg_max_gust_last_hour_time),
    avg_max_gust_today_time = VALUES(avg_max_gust_today_time),
    avg_max_apparent_temp = VALUES(avg_max_apparent_temp),
    avg_min_apparent_temp = VALUES(avg_min_apparent_temp),
    avg_max_dew_point = VALUES(avg_max_dew_point),
    avg_min_dew_point = VALUES(avg_min_dew_point),
    avg_max_gust_last_minute = VALUES(avg_max_gust_last_minute),
    avg_current_year = VALUES(avg_current_year),
    avg_thsw_index = VALUES(avg_thsw_index),
    avg_temp_trend = VALUES(avg_temp_trend),
    avg_humidity_trend = VALUES(avg_humidity_trend),
    avg_humidex_trend = VALUES(avg_humidex_trend),
    avg_hr_wind_dir_01 = VALUES(avg_hr_wind_dir_01),
    avg_hr_wind_dir_02 = VALUES(avg_hr_wind_dir_02),
    avg_hr_wind_dir_03 = VALUES(avg_hr_wind_dir_03),
    avg_hr_wind_dir_04 = VALUES(avg_hr_wind_dir_04),
    avg_hr_wind_dir_05 = VALUES(avg_hr_wind_dir_05),
    avg_hr_wind_dir_06 = VALUES(avg_hr_wind_dir_06),
    avg_hr_wind_dir_07 = VALUES(avg_hr_wind_dir_07),
    avg_hr_wind_dir_08 = VALUES(avg_hr_wind_dir_08),
    avg_hr_wind_dir_09 = VALUES(avg_hr_wind_dir_09),
    avg_hr_wind_dir_10 = VALUES(avg_hr_wind_dir_10),
    avg_leaf_wetness_vp = VALUES(avg_leaf_wetness_vp),
    avg_soil_moisture_vp = VALUES(avg_soil_moisture_vp),
    avg_avg_wind_10min = VALUES(avg_avg_wind_10min),
    avg_wet_bulb_temp = VALUES(avg_wet_bulb_temp),
    avg_latitude = VALUES(avg_latitude),
    avg_longitude = VALUES(avg_longitude),
    avg_rain_9am_reset = VALUES(avg_rain_9am_reset),
    avg_daily_high_humidity = VALUES(avg_daily_high_humidity),
    avg_daily_low_humidity = VALUES(avg_daily_low_humidity),
    avg_rain_midnight_reset = VALUES(avg_rain_midnight_reset),
    avg_daily_low_windchill_time = VALUES(avg_daily_low_windchill_time),
    avg_cost_channel_1_watts = VALUES(avg_cost_channel_1_watts),
    avg_cost_channel_2_watts = VALUES(avg_cost_channel_2_watts),
    avg_cost_channel_3_watts = VALUES(avg_cost_channel_3_watts),
    avg_cost_channel_4_watts = VALUES(avg_cost_channel_4_watts),
    avg_cost_channel_5_watts = VALUES(avg_cost_channel_5_watts),
    avg_cost_channel_6_watts = VALUES(avg_cost_channel_6_watts),
    avg_daily_wind_run_km = VALUES(avg_daily_wind_run_km),
    avg_daily_max_temp_time = VALUES(avg_daily_max_temp_time),
    avg_daily_min_temp_time = VALUES(avg_daily_min_temp_time),
    avg_avg_wind_dir_10min = VALUES(avg_avg_wind_dir_10min),
    avg_firmware_version = VALUES(avg_firmware_version);

  -- Wipe old readings
  DELETE FROM weather_readings
  WHERE DATE(FROM_UNIXTIME(ts/1000)) < CURDATE();
END;